uktrade/platform-tools

templates/addons/redis-cluster.yml
No. of replica nodes, engine and instance size configurable per env.
Automatic failover
TLS transport
Cluster can be scaled down to 1 node for non prod environments
Remaining:
incorporate into bootstrap script
=> Add HA redis cluster CFN

.gitignore, code-deploy-bootstrap.py
- Add local variable for current filepath.
- Use `current_filepath` to open JSON template files.
- This script can be called from anywhere, e.g. application and deploy repositories.
=> Update `create-deploy-role` to be callable from anywhere

buildspec.yml
- Add `buildspec` configuration file for CodeBuild project.
- Automates pulling Docker image from DockerHub to push to public ECR.
Opinions/thoughts on putting the `buildspec` file in a `paketo` directory rather than in the root directory?
=> GPM-472 Add Paketo `buildspec` configuration

templates/svc/manifest-public.yml
- Allow `301` and `302` success codes as well for health check in the `manifest.yml` file for a service, e.g. `web`.
=> Update health check success codes for redirect status codes

storage-plans.yaml
Volumesize key does not work with copilot-bootstrap so renaming to volume-size in storage-plans.yaml
Rename external-s3 to s3-policy
=> Updated volume-size key for opensearch and rename s3-policy

copilot-bootstrap.py, templates/storage-instructions.txt
- Update CLI output for storage instructions.
- Remove redundant instructions from CLI output when generating Copilot configuration files (`make_config`).
- Not used and conflates CLI output.
- Add link to GitHub docs for CLI output in `make_config` method.
=> Update template instructions

codebuild_cli.py
- Update `builder` image path to point to the ECR image in the `tools` AWS account.
JIRA ticket - https://uktrade.atlassian.net/browse/GPM-532
=> Update `builder` image path

templates/svc/manifest-backend.yml, templates/svc/manifest-public.yml
I think these changes should replicate the default we use in GOV.UK PaaS as closely as we can get with AWS Copilot and Elastic Container Service.
Jira ticket: https://uktrade.atlassian.net/browse/DBTP-178
=> DBTP-198 Enable Autoscaling

templates/addons/env/aurora-postgres.yml
1. env level addons don't get a name parameter, so remove this and supply the name from jinja2
2. the secret name was in the wrong place
=> Fix issues with Aurora postgres CFN template

README.md
Replace the old CodeBuild build badge with the new one. The previous CodeBuild build badge was also reporting the wrong build status.
- Update link to CodeBuild build badge.
This is how it looks now: ![](https://codebuild.eu-west-2.amazonaws.com/badges?uuid=eyJlbmNyeXB0ZWREYXRhIjoicUFCMXNSZVVUdnJuLzNHMDJlUVg4UVErbFkwT1NKa0NubUNudm9STk5makxZYUdtK0xiSmgxWXUzWUttTTdPbnprdTFVY2FJUzZXbHIyQTVkYmJtaVNJPSIsIml2UGFyYW1ldGVyU3BlYyI6IkxYaUFJczFoQitodytUTHAiLCJtYXRlcmlhbFNldFNlcmlhbCI6MX0%3D&branch=main)
=> Update CodeBuild build badge

templates/addons/env/redis-cluster.yml
Also the output is not needed for env addons
NOTE: This will cause problems for already deployed stacks which will prepend rediss:// to the URL in settings.py
=> Prepend rediss:// to Redis URL

templates/addons/env/rds-postgres.yml, templates/addons/env/s3.yml, templates/addons/svc/s3-policy.yml
Now we have the `check-cloudformation lint` command, it seems appropriate to make it pass.
=> DBT-149 Address cfn-lint findings

templates/addons/env/opensearch.yml
The error was due to having two SSM parameters with the same SSM name, even though CFN conditions meant that only one parameter would be active.
The solution was to use an Fn::if statement to select the endpoint url from the HA or non HA opensearch domain resource based on the EnableHA condition.  However, this resulted in another issue (possibly a CFN bug, or limitation) due to a Fn:If and a complicated nested statement. To solve this I created an intermediate SSM parameter which stores the domain endpoint url, then a final config parameter which retrieves the endpoint url, and the username and password from secrets manager.  We use one secrets manager secret and two SSM parameters, which is not ideal, but required to overcome limitations in cloudformation.
=> Fix "duplicate SSM parameter name" issue in Opensearch addon template

README.md
Because people landing at the repository root in GitHub might get confused.
=> Clearly signpost the documentation for using the package from the main README

buildspec.test.yml, pyproject.toml
- Update `copilot-helper` script entrypoint
- The entrypoint was still referencing `cli` although it was renamed to `copilot_helper` which caused the script to not work.
- Upgrade version from `0.1.5` -> `0.1.6`
=> Update `copilot-helper` entrypoint

.pre-commit-config.yaml, commands/check_cloudformation.py, commands/copilot_cli.py, pyproject.toml, tests/test_check_cloudformation.py, tests/test_copilot_cli.py
- Add `addons.parameters.yml` to be copied over in the `make-storage` command
- This file is copied over if the storage type is NOT `s3` or `s3-policy`.
- This file is also ignored when running `cfn-lint` for the `test-application`.
- 
- Update version from `0.1.8` -> `0.1.9`
- Update `pre-commit` configuration for `isort` to use the `black` profile
- `black` and `isort` had conflicting changes in `test_check_cloudformation.py`.
=> Update `make-storage` method

commands/dns_cli.py, pyproject.toml, tests/test_dns_cli.py
For https://uktrade.atlassian.net/browse/DBTP-343
I should have tested my code manually, there were extra hyphen separated things on the end of the cluster and service ARNs in the real world which are not included in the unit tests.
=> DBTP-343 Correct Handling of hyphens when getting Load Balancer details

buildspec.yml, commands/dns_cli.py, commands/utils.py, migration-tools/build-copilot-config.py, pyproject.toml
For https://uktrade.atlassian.net/browse/DBTP-344, which I think we can maybe defer for today, but need to address pretty soon.
Address some issues we hit when using the `check-domain` command to create a new environment.
Increases the "helpfulness" of the output.
No tests have failed as a result of these changes 😬 
This is in no way the whole of the work required for the ticket, just an expedient attempt to unblock us deploying a new environment while @WillGibson got a lot more familiar with the workings of dns_cli.py than he was before 🤣
=> DBTP-344 Expedient pass at making `copilot-helper domain check-domain` work

commands/templates/svc/manifest-public.yml, tests/fixtures/test_service_manifest.yml, tests/test_bootstrap_cli.py
As discussed in Slack, we will use the defaults and revisit this as required on a per application basis.
=> Use defaults for public service healthcheck timeout and interval

commands/copilot_cli.py, commands/templates/storage-instructions.txt, pyproject.toml, tests/test_copilot_cli.py
- Update `make-storage` command
- update the storage instructions template to display additional output for database/Postgres storage types.
- Update the format of the secrets as well to match the secrets formatting convention.
=> Update `make-storage` command

commands/bootstrap_cli.py, tests/test_bootstrap_cli.py
- Update `copy-secrets` command to properly set tags
- Display a message if the parameter/secret already exists in Parameter Store for the target environment.
- Creates the parameter/secret only if it does not exist already.
This has been manually tested as well. We still need to test the utils method - is that part of this ticket or another?
Jira ticket - https://uktrade.atlassian.net/browse/DBTP-350
=> Update `copy-secrets` command

commands/addons-template-map.yml, commands/bootstrap_cli.py, commands/check_cloudformation.py, commands/copilot_cli.py, commands/default-storage.yml, commands/schemas/storage-schema.json, commands/templates/addons/svc/appconfig-ipfilter.yml, commands/templates/svc/manifest-public.yml, commands/utils.py, commands/waf_cli.py, pyproject.toml, tests/conftest.py, tests/fixtures/invalid_cloudformation_template.yml, tests/fixtures/test_service_manifest.yml, tests/test-docs/example.md, tests/test_bootstrap_cli.py, tests/test_check_cloudformation.py, tests/test_copilot_cli.py, tests/test_storage_validation.py, utils/create_command_docs.py
Added an addons-template-map.yml file to determine which cloudformation files should be written on the environment and service level for each addon type.
This has simplified the make-storage command and removed the hard coded conditional logic, e.g `if storage_type == "s3-plicy": .... `
There is a failing WAF test, this appears to predate this PR.
=> Refactor template logic

commands/check_cloudformation.py, commands/copilot_cli.py, commands/default-storage.yml, commands/schemas/storage-schema.json, commands/templates/addons/svc/appconfig-ipfilter.yml, commands/templates/svc/manifest-public.yml, commands/utils.py, commands/waf_cli.py, pyproject.toml, tests/fixtures/invalid_cloudformation_template.yml, tests/fixtures/test_service_manifest.yml, tests/test_bootstrap_cli.py, tests/test_check_cloudformation.py, tests/test_copilot_cli.py, tests/test_storage_validation.py, tests/test_waf_cli.py
This PR adds the appconfig and ipfilter containers.  The new IP filter logic is always inline, but IP filtering can be disabled by setting the an env var: `IPFILTER_ENABLED=False`.  The IP filter can also be disabled on a per environment basis. When disabled the IP filter reverse proxies traffic to the service.
=> Add new ip filter config with appconfig container

commands/COMMANDS.md, commands/conduit_cli.py, pyproject.toml, tests/test_conduit_cli.py
Add a command line option to use a custom postgres secret when connecting via `copilot-helper conduit tunnel`.
Some setups may involve a custom set postgres credentials name in secrets manager as this is configurable in addon stack cloudformation templates.
Add an optional flag to the `copilot-helper conduit tunnel` command and pass this through to `get_postgres_secret`, defaulting to `POSTGRES`.
=> Allow configurable postgres secret param

.gitignore, buildspec.pypi.yml, pyproject.toml, tests/utils/fixtures/pyproject.toml, tests/utils/fixtures/pyproject_malformed.toml, tests/utils/fixtures/pyproject_no_version.toml, tests/utils/test_check_pypi.py, utils/check_pypi.py
This PR creates a codebuild pipline that runs the tests using tox, and if successful and the version number has not already been published will build and push the package to PyPI.
The utility script is to facilitate getting the package version from the pyproject.toml and compare it to the published versions from the PyPI RSS feed.
=> PyPI package publishing

README.md
Test that the test pipeline does not trigger, but the docker image copy and PyPI publish ones do.
=> Test reconfigured pipeline triggers.

commands/conduit_cli.py, pyproject.toml, tests/conftest.py, tests/test_conduit_cli.py
Bind conduit tasks to a specific environment and application as well as the current addon binding.
Currently, if I start a conduit in the dev environment and then attempt to start a conduit in the staging environment I will connect to the dev environment conduit task. This is not desirable.
Add application and environment name to the conduit task group name in ECS.
=> Fix: bind conduit tasks to app and env

commands/templates/addons/env/opensearch.yml, pyproject.toml
Fix generation of the ARN for opensearch access policy.
The name pattern is `[truncated 15 chars of resource name]-[12 random chars]`.
Using jinja's `truncate()` filter.
=> fix: opensearch resource policy ARN template

commands/templates/addons/env/addons.parameters.yml, commands/templates/addons/env/opensearch.yml, commands/templates/env/manifest.yml, pyproject.toml, tests/fixtures/make_addons/config/copilot/environments/development/manifest.yml, tests/fixtures/make_addons/expected/environments/addons/addons.parameters.yml, tests/fixtures/make_addons/expected/environments/addons/my-opensearch-with-a-long-name.yml, tests/fixtures/make_addons/expected/environments/addons/my-opensearch.yml, tests/fixtures/production_environment_manifest.yml, tests/fixtures/test_environment_manifest.yml
- Revert to using the default VPC configuration
- The default is 2 public and 2 private subnets.
- Update version from `0.1.32` -> `0.1.33`
Jira ticket - https://uktrade.atlassian.net/browse/DBTP-433
=> DBTP-433 - Revert VPC configuration to use default configuration

commands/templates/addons/env/opensearch.yml, pyproject.toml, tests/fixtures/make_addons/expected/environments/addons/my-opensearch-longer.yml, tests/fixtures/make_addons/opensearch_addons.yml, tests/test_copilot_cli.py
Fix addon template access policy generation for opensearch.
#Why?
Currently truncate will only truncate to 15 chars if the string is more than 20 chars in length, we need it to hard limit to 15 chars.
#How?
Use an array slice to truncate instead of truncate.
=> fix: truncate opensearch names under 20 chars

commands/templates/addons/env/aurora-postgres.yml, commands/templates/addons/env/opensearch.yml, commands/templates/addons/env/rds-postgres.yml, pyproject.toml, tests/fixtures/make_addons/expected/environments/addons/my-aurora-db.yml, tests/fixtures/make_addons/expected/environments/addons/my-opensearch-longer.yml, tests/fixtures/make_addons/expected/environments/addons/my-opensearch.yml, tests/fixtures/make_addons/expected/environments/addons/my-rds-db.yml
Do not allow using characters in addons credentials that cause an invalid connection url to be generated.
Python URL library fails to parse a URL where the password contains `/`.
Use the `ExcludeCharacters` property on the `AWS::SecretsManager::Secret` resource to exclude characters that are not valid in a URL.
=> fix: passwords in urls with invalid characters

commands/templates/addons/env/aurora-postgres.yml, commands/templates/addons/env/opensearch.yml, commands/templates/addons/env/rds-postgres.yml, pyproject.toml, tests/fixtures/make_addons/expected/environments/addons/my-aurora-db.yml, tests/fixtures/make_addons/expected/environments/addons/my-opensearch-longer.yml, tests/fixtures/make_addons/expected/environments/addons/my-opensearch.yml, tests/fixtures/make_addons/expected/environments/addons/my-rds-db.yml
Subsequent to #158 we found a number of other symbols that are invalid in URLs: 
```
?&`><:|#
```
This PR adds those to all addons templates that need them.
=> fix: more url invalid symbols for passwords in urls

commands/COMMANDS.md, commands/codebuild_cli.py, pyproject.toml
- Update CodeBuild command to use the `latest` image tag for the `ci-image-builder` by default
- This removes the need for the `--builderimage` flag.
- Bump version from `0.1.38` -> `0.1.39`
=> Update CodeBuild command

commands/templates/addons/env/aurora-postgres.yml, commands/templates/addons/env/opensearch.yml, commands/templates/addons/env/rds-postgres.yml, tests/fixtures/make_addons/expected/environments/addons/my-aurora-db.yml, tests/fixtures/make_addons/expected/environments/addons/my-opensearch-longer.yml, tests/fixtures/make_addons/expected/environments/addons/my-opensearch.yml, tests/fixtures/make_addons/expected/environments/addons/my-rds-db.yml
The ExcludeCharacters field needed updating, as python's urlparse function was failing to parse opensearch URLs that contain the generated password. In this case, it was square brackets that were causing the issue, but i have excluded parentheses and braces as well to ensure we don't hit this issue again.
=> Added further characters to exclude from passwords

dbt_copilot_helper/schemas/addons-schema.json, dbt_copilot_helper/templates/addons/env/aurora-postgres.yml, pyproject.toml, tests/fixtures/make_addons/expected/environments/addons/my-aurora-db.yml
From the [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbinstance.html): "Not applicable. Amazon Aurora storage is replicated across all of the Availability Zones and doesn't require the MultiAZ option to be set."
=> remove multiaz option from aurora template

buildspec.pypi.yml, tests/test_command_check_cloudformation.py
Changes in the DBTP-456 ticket changed how the linting is done to make it applicable to arbitrary projects. A side effect of this is that I missed changing the command in one of the pipelines.
This change does 2 things:
- A small refactoring of the fixtures in the check-cloudformation tests that I was working on.
- Removing the lint check entirely from the pipeline, since wherever it was used it also ran the unit tests which do the same lint check on the same directory structure (tests/test-application)
=> Fix pipeline

dbt_copilot_helper/commands/conduit.py, pyproject.toml, tests/test_command_conduit.py
Currently secrets manager is checked first, which runs into issue because the opensearch addons have both a secrets manager and parameter store variable. The secret is json storing only username and password whereas the parameter store has the actual connection string.
=> Conduit order of connection strings

dbt_copilot_helper/commands/copilot.py, dbt_copilot_helper/schemas/addons-schema.json, pyproject.toml, tests/fixtures/make_addons/expected/environments/addons/my-opensearch.yml, tests/fixtures/make_addons/opensearch_addons.yml
- Allow overriding plan default volume size for opensearch in `addons.yml`.
- Fix a bug where overriding the addon plan also overrode the plans values for subsequent addons of the same type.
=> Fix: allow setting opensearch volume size

buildspec.yml
https://uktrade.atlassian.net/browse/DBTP-430
The previous builder image was archived and not receiving updates, meaning ecr images built with it contained increasing numbers of vulnerabilities.
=> DBTP-430 Update Paketo builder and run images

dbt_copilot_helper/templates/addons/env/aurora-postgres.yml, dbt_copilot_helper/templates/addons/env/rds-postgres.yml, poetry.lock, pyproject.toml, tests/fixtures/make_addons/expected/environments/addons/my-aurora-db.yml, tests/fixtures/make_addons/expected/environments/addons/my-rds-db.yml
https://uktrade.atlassian.net/browse/DBTP-497
[Original pen test report](https://dbis.sharepoint.com/sites/CyberTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCyberTeam%2FShared%20Documents%2FDDaT%20SharePoint%20folder%2F21%2D%20Pentests%2F2022%2D2023%2F11%2E%20DBT%20Paas%2FUKP%2D2345%2DRPT%2D01%20Department%20for%20Business%20and%20Trade%20DBT%20PaaS%20IT%20Health%20CHECK%20Report%20v1%2E0%2Epdf&parent=%2Fsites%2FCyberTeam%2FShared%20Documents%2FDDaT%20SharePoint%20folder%2F21%2D%20Pentests%2F2022%2D2023%2F11%2E%20DBT%20Paas&p=true&ga=1)
Makes RDS and aurora templates use a customer-managed KMS key, rather than the AWS default used currently.
=> DBTP-497 BSI 6.1: RDS not encrypted using customer keys

dbt_copilot_helper/commands/svc.py, tests/copilot_helper/test_command_svc.py
Addresses: https://uktrade.atlassian.net/browse/DBTP-551
When @antroy-madetech and wrote this code we thought all image repository names would include the `/web` etc. part. Turns out this is not the case and I think we can simply remove that requirement.
=> DBTP-551 Stop checking image repository name contains service name

dbt_copilot_helper/templates/addons/env/addons.parameters.yml, dbt_copilot_helper/templates/addons/env/aurora-postgres.yml, dbt_copilot_helper/templates/addons/env/rds-postgres.yml, pyproject.toml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/addons.parameters.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-aurora-db.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-rds-db.yml
- Add dependencies to PostgreSQL user custom resource
- The main/parent CloudFormation stack has the internet gateway, public routes, and public subnets, so when a `copilot env delete` is executed, the resources in the root and nested stacks are delete in parallel. This means the Lambda Function loses access to the database and also the internet without these additional dependencies.
- This change means the custom resource is deleted first along with the Parameter Store secret for the PostgreSQL application user when running `copilot env delete --name <environment>`.
- Update package version from `0.1.72` -> `0.1.73`
This is a far from ideal solution. The reason to take this approach rather than the `dependsOn` attribute within the Custom Resource is because this attribute only allows …
=> DBTP-544 - Fix custom resource deletion hanging

dbt_copilot_helper/templates/addons/env/s3.yml, pyproject.toml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-s3-bucket-with-an-object.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-s3-bucket.yml
Addresses https://uktrade.atlassian.net/browse/DBTP-545
We have CloudTrail event logging enabled for the buckets so the old school logging to an S3 bucket is redundant.
Tested on my `demodjango` environment.
=> DBTP-545 Remove old school S3 logging to an S3 bucket

dbt_copilot_helper/commands/bootstrap.py, pyproject.toml, tests/copilot_helper/test_command_bootstrap.py
This PR fixes the file not found error in repos where there is no bootstrap.yml
It pulls the app name from the copilot/.workspace file instead.
=> copy-secrets command fails without bootstrap.yml

dbt_copilot_helper/COMMANDS.md, dbt_copilot_helper/commands/codebuild.py, pyproject.toml, tests/copilot_helper/test_command_codebuild.py
https://uktrade.atlassian.net/browse/DBTP-432
Prevent users from entering secret credentials as command line options.
Documentation PR to follow.
=> DBTP-432 `copilot-helper` commands should not take credentials as arguments

dbt_copilot_helper/commands/conduit.py, pyproject.toml, tests/copilot_helper/conftest.py, tests/copilot_helper/test_command_conduit.py
Fix for a bug in the function to add delete policy to conduit CloudFormation stacks, which causes the command to fail when there's a custom addon name.
=> DBTP-571 - Fix conduit command error with custom addon name

dbt_copilot_helper/templates/pipelines/codebase/overrides/package-lock.json, dbt_copilot_helper/templates/pipelines/codebase/overrides/package.json, dbt_copilot_helper/templates/pipelines/codebase/overrides/stack.ts, dbt_copilot_helper/templates/pipelines/codebase/overrides/types.ts, pyproject.toml
- Set the `aws-cdk-lib` version to 2.56.0 only (copilot isn't compatible with newer versions)
- Expose the environment variable `ECR_REPOSITORY` in the build image job
- Ensure the pipeline only includes jobs relevant to the service
- Allow setting a list of account ids in the pipelines configuration so we can set ECR repository permissions for cross-account access
=> DBTP-586 Fixes to generated build files

dbt_copilot_helper/templates/addons/env/opensearch.yml, pyproject.toml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-opensearch-longer.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-opensearch.yml
- Update OpenSearch template to change specific properties rather than conditionally defining a separate instance. This allows the instance count to change without CloudFormation replacing the resource
- Bump version number
=> DBTP-590 - Update OpenSearch template to allow scaling without instance replacement

dbt_copilot_helper/templates/pipelines/codebase/overrides/package-lock.json, dbt_copilot_helper/templates/pipelines/codebase/overrides/package.json
Reverts uktrade/copilot-tools#244
As this version does not work with copilot, must be reverted.
=> Revert "Bump aws-cdk-lib from 2.56.0 to 2.80.0 in /dbt_copilot_helper/templates/pipelines/codebase/overrides"

dbt_copilot_helper/commands/conduit.py, dbt_copilot_helper/utils/application.py, dbt_copilot_helper/utils/aws.py, pyproject.toml, tests/copilot_helper/conftest.py, tests/copilot_helper/fixtures/dummy_aws_config.ini, tests/copilot_helper/test_command_check_cloudformation.py, tests/copilot_helper/test_command_conduit.py, tests/copilot_helper/test_copilot_helper.py, tests/copilot_helper/utils/test_application.py, tests/copilot_helper/utils/test_aws.py
- Allow conduit to connect to addons provisioned in accounts other than the main application account (production for example).
- Implementation of an `Application` class and loader allowing easy and lazy-loading session access.
- Minor tweak to `fakefs` fixture to lazy-load real directories.
=> DBPT-589 conduit across accounts

dbt_copilot_helper/templates/pipelines/codebase/overrides/stack.ts, pyproject.toml
- Fix an error when no accounts are configured (for situations where there is only one account in the application).
- Remove repetition when creating required pipeline stages for existing and newly created pipelines.
- Push up a codebase configuration including information about all pipelines that deploy that codebase.
=> DBTP-464 Fix no accounts in pipelines config raising error

tests/copilot_helper/conftest.py
- Unset the `AWS_PROFILE` environment variable
- This fixes an issue when this is set locally, and for most it will be set if we are using `direnv` which loads the `.envrc` file.
=> Bugfix: Unset `AWS_PROFILE` in `conftest.py`

dbt_copilot_helper/COMMANDS.md, dbt_copilot_helper/commands/dns.py, pyproject.toml, tests/copilot_helper/conftest.py, tests/copilot_helper/test_command_dns.py
Ticket is: [DBTP-444](https://uktrade.atlassian.net/browse/DBTP-444)
Copied over from the ticket (agreed on a thread in slack):
- The dev base domain will always be uktrade.digital
- Prod base domains will always be one of: prod.uktrade.digital, great.gov.uk, trade.gov.uk
- For dev, subdomains will always be <name>.<env>.uktrade.digital
- For prod, subdomains will always be <name>.<base_domain. Deeper names will be added as records (such as `v2.app.trade.gov.uk`)
- base_domain can be inferred from the subdomain if we keep a dict of base_domains vs domain_profiles in the codebase.
- We don’t need the functionality to be able to pass in an entire domain_profile, so domain_profile can also be inferred from the subdomain. 
- Note: this means we can remove both --base-domain and …
=> Extra prod domain bug

dbt_copilot_helper/COMMANDS.md, dbt_copilot_helper/commands/codebase.py, pyproject.toml, tests/copilot_helper/test_command_codebase.py
Adds new command:
```shell
copilot-helper codebase list --app <app> [--with-images] 
```
Will list codebases associated with an application. The optional flag `--with-images` will list, with links, the commits for which an image has been built.
Example output for demodjango:
```console
copilot-helper codebase list --app demodjango --with-images
Checking AWS connection for profile "foo"...
Credentials are valid.
Logged in with AWS account id: xxxxxxxxx
User: xxxxxxxxxxx
The following codebases are available:
- application (https://github.com/uktrade/demodjango)
- https://github.com/uktrade/demodjango/commit/ee4a82c - published: 2023-11-30 15:39:43+00:00
- https://github.com/uktrade/demodjango/commit/0f3e90f - published: 2023-11-09 10:58:49+00:00
- …
```
=> Codebase list command

dbt_copilot_helper/commands/bootstrap.py, dbt_copilot_helper/templates/svc/overrides/cfn.patches.yml, pyproject.toml
Small change to bootstrap to include service level cfn patching to rename log group name with hypens to /'s
=> Add service level patching for renaming service log group name

dbt_copilot_helper/commands/conduit.py, pyproject.toml, tests/copilot_helper/test_command_conduit.py
- Can't add forward slashes to the conduit log group names
- Instead adding the information in the correct format to the log group subscription filter name
=> DBTP-628 - Update conduit log naming

dbt_copilot_helper/templates/env/manifest.yml, pyproject.toml, tests/copilot_helper/fixtures/make_addons/config/copilot/environments/development/manifest.yml, tests/copilot_helper/fixtures/newenv_environment_manifest.yml, tests/copilot_helper/fixtures/production_environment_manifest.yml, tests/copilot_helper/fixtures/test_environment_manifest.yml
Update ALB log bucket name to `dbt-access-logs` to match bucket in central logging account
=> DBTP-625 - Update ALB log bucket name

dbt_copilot_helper/commands/dns.py, pyproject.toml, tests/copilot_helper/test_command_dns.py
When multiple domains were present with the same base domain, the tool would error. This fixes it so that it only errors when the base domains are different.
=> Multiple domain bugfix

copilot_helper.py, dbt_copilot_helper/COMMANDS.md, dbt_copilot_helper/commands/environment.py, dbt_copilot_helper/templates/svc/maintenance_pages/default.html, dbt_copilot_helper/templates/svc/maintenance_pages/migration.html, pyproject.toml, tests/copilot_helper/test_command_environment.py, tests/copilot_helper/test_copilot_helper.py
Adds two commands:
`copilot-helper environment offline --app <app> --env <env> [--template (default|migration)]`
Take an environment offline by setting a fixed response at the load balancer.
`copilot-helper environment online --app <app> --env <env>`
Take an environment online by removing the currently set maintenance page.
=> DBTP-620 load balancer maintenance pages

dbt_copilot_helper/commands/dns.py, pyproject.toml, tests/copilot_helper/test_command_dns.py
very quick PR to move the prod.uktrade.digital domain to live, as this is where the R53 domain is now.
=> move prod domain to live aws

dbt_copilot_helper/commands/codebase.py, pyproject.toml, tests/copilot_helper/expected_files/.copilot/config.yml
To avoid time wasting confusion when people run `copilot-helper codebase prepare` and it uses the latest version of paketobuildpacks/builder-jammy-base, which is not compatible with the latest version of `fagiani/apt`.
```
ERROR: failed to build: validating buildpacks: buildpack 'fagiani/apt@0.2.5' (Buildpack API 0.4) is incompatible with lifecycle '0.18.2' (Buildpack API(s) 0.7, 0.8, 0.9, 0.10)
```
Will be addressed properly under https://uktrade.atlassian.net/browse/DBTP-351.
=> DBTP-351 Temporarily restrict max paketobuildpacks/builder-jammy-base to 0.4.240

dbt_copilot_helper/COMMANDS.md, dbt_copilot_helper/commands/conduit.py, pyproject.toml, tests/copilot_helper/test_command_conduit.py
To reduce confusion and rabbit holing until https://uktrade.atlassian.net/browse/DBTP-448 is actioned.
=> DBTP-448 Make conduit --addon-name required

dbt_copilot_helper/COMMANDS.md, dbt_copilot_helper/commands/bootstrap.py, pyproject.toml
No tests removed as none exist for running the command without `--env` set.
=> DBTP-648 must specify `--env` when migrating secrets

dbt_copilot_helper/COMMANDS.md, dbt_copilot_helper/commands/svc.py, pyproject.toml, tests/copilot_helper/test_command_svc.py
Changed behaviour to reject latest tag and to default to the tag-latest tag.
Reject the tag-latest tag if there is no corresponding commit- tag
=> Use tag-latest rather than latest as the default tag

dbt_copilot_helper/commands/copilot.py, pyproject.toml, tests/copilot_helper/test_command_copilot.py
Add an `is_service` check to `list_copilot_local_services`, so that `make-addons` can distinguish between services and scheduled jobs.
=> DBTP-675 make-addons generates addons and overrides for scheduled jobs

Dockerfile.debian, dbt_copilot_helper/templates/svc/manifest-backend.yml, dbt_copilot_helper/templates/svc/manifest-public.yml, pyproject.toml, tests/copilot_helper/fixtures/test_service_manifest.yml
- Add OTel env vars to manifest template files
- This is to setup observability (X-Ray) for services.
- The sampling ratio is set at a default of 5%.
- Add `Dockerfile.debian` file
- This is currently used for `copilot-python` as the Alpine Dockerfile does not support installing gRPC within a `poetry` context. This image should also be used for this repo in the near future to avoid issues like this from reoccurring.
=> DBTP-660 Add OpenTelemetry variables to manifest files

dbt_copilot_helper/commands/dns.py, pyproject.toml, tests/copilot_helper/test_command_dns.py
- Add test for creating a certificate when a record already exists
- Fix error in `domain configure` command when re-creating a certificate and a record already exists
=> DBTP-672 - Domain configure error creating certificate

buildspec.pypi.yml
- Update the RegEx to work with the `debian` image.
- Reference: https://github.com/uktrade/copilot-tools/blob/a23607324d8eb7e7118150b6edd67c2640a8b4ba/buildspec.test.yml#L7
=> Update PyPI buildspec for `debian` image

buildspec.pypi.yml, buildspec.test.yml
To verify the version of Python being used, especially during the publish stage where we are seeing `ModuleNotFoundError: No module named 'tomllib'`,
=> Add some Python version checking to some build pipelines

dbt_copilot_helper/commands/bootstrap.py, dbt_copilot_helper/utils/cloudfoundry.py, pyproject.toml, tests/copilot_helper/test_command_bootstrap.py, tests/copilot_helper/utils/test_cloudfoundry.py
Previously a stack trace was displayed on the screen if you were not logged into Cloud Foundry before running this command. This PR makes the error message more useful and less noisy.
=> Better `copilot-helper bootstrap migrate-secrets` cloudfoundry errors

dbt_copilot_helper/templates/addons/env/aurora-postgres.yml, dbt_copilot_helper/templates/addons/env/opensearch.yml, dbt_copilot_helper/templates/addons/env/rds-postgres.yml, dbt_copilot_helper/templates/addons/env/redis-cluster.yml, pyproject.toml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-aurora-db.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-opensearch-longer.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-opensearch.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-rds-db.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-redis.yml
- Fix so bumping patch version number
- All resources must be prefixed with `{{ addon_config.prefix }}` otherwise they will conflict
- Haven't added an overall test to check this due to time constraint, though maybe one could be implemented in future.
=> fix: all addon resource names must be globally unique [DBTP-734]

dbt_copilot_helper/default-addons.yml, pyproject.toml, tests/copilot_helper/test_command_copilot.py
This change makes the monitoring addon part of the default addons, it's backwards compatible with deploy repos that currently have a monitoring addon configured.
=> fix: enable monitoring addon by default

dbt_copilot_helper/templates/addons/env/aurora-postgres.yml, dbt_copilot_helper/templates/addons/env/rds-postgres.yml, pyproject.toml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-aurora-db.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-rds-db.yml
- bump patch version as this is a fix
- make resource names for lambda and lambda role unique to each addon name
=> fix: lambda related resource names must be unique [DBTP-736]

dbt_copilot_helper/templates/svc/overrides/cfn.patches.yml, pyproject.toml, tests/copilot_helper/fixtures/make_addons/expected/web/overrides/cfn.patches.yml
Addresses https://uktrade.atlassian.net/browse/DBTP-438
Adds the required override blocks to stop us having to manually replace them every time we run `make-addons`.
=> DBTP-438 Allow service containers to use temporary file system

README.md, images/debian-python/Dockerfile.debian, images/debian-python/README.md
To support our pull request and regression test pipelines.
Has already been published and tested.
=> DBTP-681 Add AWS Copilot CLI to debian/python image

.github/workflows/test.yml, buildspec.test.yml
Approximately 6 times faster than running them in serial in CodeBuild, which we can save for running the regression tests.
=> DBTP-770 Run unit tests in parallel by Python version in GitHub Actions

dbt_copilot_helper/COMMANDS.md, dbt_copilot_helper/commands/copilot.py
Small PR to suggest the removal of what doesn't seem to be a used param / argument for make_addons
=> chore: Remove -d / --directory arguments and default param from make_addons

dbt_copilot_helper/templates/addons/env/rds-postgres.yml, pyproject.toml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-rds-db.yml
Currently RDS addons only work if you deploy postgres 13, this PR resolves that issue by using the set version of postgres when generating the postgres parameter group.
=> fix: RDS parameter group family

.github/workflows/quality-checks.yml, pytest.ini
Me and @JohnStainsby noticed that currently all 4 test runs are run with python version `3.10.12` so effectively, 3 are redundant.
This PR addresses this.
=> chore: Ensure python versions are installed and used when running tests

dbt_platform_helper/templates/addons/env/opensearch.yml, dbt_platform_helper/templates/addons/env/redis-cluster.yml, dbt_platform_helper/utils/validation.py, tests/platform_helper/fixtures/make_addons/expected/environments/addons/my-opensearch-longer.yml, tests/platform_helper/fixtures/make_addons/expected/environments/addons/my-opensearch.yml, tests/platform_helper/fixtures/make_addons/expected/environments/addons/my-redis.yml, tests/platform_helper/fixtures/make_addons/opensearch_addons.yml, tests/platform_helper/test-application-deploy/addons.yml
Update code with latest supported versions of Redis and opensearch engines as per [DBT-829](https://uktrade.atlassian.net/browse/DBTP-829)
Updated references to these engines also.
Wondering if we should remove all references to now unsupported versions of engines form the code?
Will this break anything?
=> chore: update opensearch & Redis supported versions & references

poetry.lock, pyproject.toml, pytest.ini, tests/platform_helper/conftest.py, tests/platform_helper/custom_resources/test_s3_object.py, tests/platform_helper/test_command_application.py, tests/platform_helper/test_command_bootstrap.py, tests/platform_helper/test_command_conduit.py, tests/platform_helper/test_command_copilot.py, tests/platform_helper/test_command_dns.py, tests/platform_helper/utils/test_application.py, tests/platform_helper/utils/test_aws.py, tests/platform_helper/utils/test_validation.py
https://uktrade.atlassian.net/browse/DBTP-906
Bumping moto silences CryptographyDeprecationWarning - requires replacing decorators with all-purpose `mock_aws`
Running tests with 3.12 gives hundreds of warnings - silenced a few of these in `pytest.ini`
=> test: fix pytest warnings

tests/platform_helper/test_command_generate.py
The problem was that `generate_platform_helper_version_file` wasn't being mocked and `tmp_path` / `fakefs`'s fixture were not passed in. This was causing all sorts of weird behaviours with the `.platform-helper-version` file being created in random places and remaining there as the filesystem wasn't a temporary throw away one. On top of this, `dbt-platform-helper` was not being found by tests. 
These errors were not easy to find due to pytest's stderr capture masking the real problem
=> fix: DPTP-923 Mock function that causes problems in generate tests

dbt_platform_helper/templates/env/overrides/package-lock.json, dbt_platform_helper/templates/env/overrides/package.json, dbt_platform_helper/templates/pipelines/codebase/overrides/package-lock.json, dbt_platform_helper/templates/pipelines/codebase/overrides/package.json
I raised https://github.com/aws/copilot-cli/issues/5767 and it was addressed in https://github.com/aws/copilot-cli/pull/5777/files
~TBC: Is this backwards breaking as it it requires https://github.com/aws/copilot-cli/releases/tag/v1.33.3 or newer?~
* Update the version of AWS Copilot in the `.copilot-version` and `.tool-versions` files for for your `<application>-deploy` codebase to 1.33.3 or newer
* [Regenerate the pipeline configuration](https://platform.readme.trade.gov.uk/components/deployment-automation/configuring-pipelines/#generate-copilot-configuration)
* [Redeploy the pipelines](https://platform.readme.trade.gov.uk/components/deployment-automation/configuring-pipelines/#deploy-pipelines)
=> fix!: Update aws-cdk and aws-cdk-packages to fix CVE 5777

dbt_platform_helper/COMMANDS.md, dbt_platform_helper/commands/environment.py, tests/platform_helper/test_command_environment.py
Non-prod envs all use the same vpc and expect the vpc name to match AWS account name e.g. `intranet`, whereas prod env expects format `intranet-prod`
Also removes commented out crap from previous PR
=> fix: env generate vpc name not found bug

dbt_platform_helper/COMMANDS.md, dbt_platform_helper/commands/config.py, tests/platform_helper/test_command_config.py
I would've added more unit tests for the helper methods, but `moto` doesn't support any of the methods used and the tests seemed fairly trivial by the time I'd patched that moto logic.
=> feat: DBTP-933 Add option to Platform-helper to manage .aws/config file

dbt_platform_helper/commands/conduit.py, tests/platform_helper/conftest.py
Redis and Opensearch parameters have ENDPOINT suffix now but conduit hasn't been updated.
This PR resolves issues connecting to Redis and Opensearch resources.
=> fix: redis and opensearch parameters missing ENDPOINT suffix

dbt_platform_helper/COMMANDS.md, dbt_platform_helper/commands/notify.py, dbt_platform_helper/utils/arn_parser.py, platform_helper.py, tests/doubles/slack.py, tests/platform_helper/test_command_notify.py, tests/platform_helper/test_platform_helper.py, tests/platform_helper/utils/test_arn_parser.py
Ported from ci-imagebuilder. Modified to be commands, but core code is broadly the same.
The main differences are that the command explicitly has all arguments and options supplied on the cli, rather than having variables coming in via env vars.
=> feat: Add slack notification commands

dbt_platform_helper/addon-plans.yml, dbt_platform_helper/addons-template-map.yml, dbt_platform_helper/templates/addons/svc/prometheus-policy.yml, dbt_platform_helper/utils/validation.py, tests/platform_helper/fixtures/make_addons/expected/web/addons/prometheus.yml, tests/platform_helper/fixtures/make_addons/prometheus_policy_addons.yml, tests/platform_helper/test_command_copilot.py, tests/platform_helper/utils/fixtures/addons_files/prometheus_policy_addons_bad_data.yml, tests/platform_helper/utils/test_validation.py
This PR adds a service level extension type called `prometheus-policy` that allows allows the ECS task to assume a cross account role that enables the ADOT AWS Distro for Open Telemetry sidecar container to write metrics into Prometheus.
Additional configuration is required to use Prometheus and will be added to the platform documentation soon.
Some changes may be made to this logic in the future as we explore using Prometheus/Grafana for container insights metrics.  This initial PR will unblock datahub and allow them to set up their RQ dashboard in Grafana.
=> feat: Add prometheus-policy extension type

dbt_platform_helper/commands/conduit.py, tests/platform_helper/conftest.py
Fix additional reference to parameter path for opensearch and redis conduit sessions
=> fix: DBTP-1053 - Fix opensearch conduit parameter path

dbt_platform_helper/COMMANDS.md, dbt_platform_helper/commands/environment.py
Addresses a direct request in slack.
The dmas-migration template option is missing and needs to be added to enable DMAS cutover tomorrow.
I'm not sure if tests are needed, or whether this option will be removed or made a bit more generic post migration. 
It is an additional fix that allows the changes in this PR to work correctly: https://github.com/uktrade/platform-tools/commit/8b271c9f6bfd04974c3d8794b2f646dafc4fa9ac\
Post DMAS go live we should probably look at a more general solution - maybe allowing a template to be supplied, or a parameter for a date that the service will unavailable. 
---
=> fix: add dmas-migration to available environment template options

buildspec.pypi.yml
The unit tests are automatically run before and after merge to `main`.
The regression tests should be manually triggered before merging to `main` and are automatically run after merging to `main`.
All we achieve by running them in the publish pipeline is to make it take half an hour to publish a release.
---
=> test: Remove tests from publish pipeline

images/conduit/opensearch/Dockerfile, images/conduit/opensearch/entrypoint.sh
When terraforming OpenSearch we set the master password and encode it when saving it to the parameter store. This fix decodes the connection string in the conduit session before it's written to the opensearch-cli config file.
https://uktrade.atlassian.net/browse/DBTP-1054
Also updating the opensearch-cli to the latest version, which is backwards compatible
https://github.com/opensearch-project/opensearch-cli/releases/tag/v1.2.0
Related docs change
https://github.com/uktrade/platform-documentation/pull/322
---
=> fix: DBTP-1504 - Fix unauthorised error in OpenSearch conduit CLI

dbt_platform_helper/commands/environment.py
Addresses https://uktrade.atlassian.net/browse/DBTP-1148
Moved check into generate function
---
=> fix: DBTP-1148 platform-helper environment generate should exit it not logged in

dbt_platform_helper/commands/conduit.py
Addresses [DBPT-1128](https://uktrade.atlassian.net/browse/DBTP-1128).
Adds in the --execution-role switch to the copilot task run command, which utilises a custom IAM role (created via Terraform) to run the ECS tasks.
As this is a bug fix there are no changes to the existing tests; and no updates to the existing documentation
Regression tests have been completed [here](https://eu-west-2.console.aws.amazon.com/codesuite/codebuild/763451185160/projects/platform-tools-test/build/platform-tools-test%3Afe9f874a-7cc0-407b-80b5-d5c062f6277e/?region=eu-west-2)
---
=> fix: DBPT-1128 Connection Error when connecting to Redis via Conduit

dbt_platform_helper/templates/environments/main.tf
This bumps the version of terraform-platform-modules used in the environment manifest template.
---
=> chore: Bump terraform platform modules version

dbt_platform_helper/templates/pipelines/codebase/overrides/buildspec.image.yml
Addresses [DBTP-1187 Set up slack alert for failed image building pipelines](https://uktrade.atlassian.net/browse/DBTP-1187)
---
=> chore: Add slack notification for codebuild build failure

README.md
No ticket.
This has been on my to do list for a couple of weeks.
---
=> docs: Update regression tests documentation

dbt_platform_helper/templates/pipelines/codebase/overrides/stack.ts
Addresses [DBTP-655](https://uktrade.atlassian.net/browse/DBTP-655)
- The `pipeline-<application>-<pipeline>-BuildProjectRole` role is auto generated by AWS Copilot when you execute `copilot pipeline deploy`
- The `pipeline-<application>-<pipeline>-CodeBuildPolicy` is attached to that role & includes ECR permissions. 
- Both the demodjango application image build codebuild job and the pipeline deploy codebuild job use `pipeline-<application>-<pipeline>-BuildProjectRole` as their service role. This service role did not have permission to delete images in ECR.
- AWS Copilot-cli role policy is [here](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/cicd/partials/role-policy-document.yml).
- I've started a …
=> chore: Dbtp-655 image building pipeline unable to delete previous cache image

dbt_platform_helper/commands/conduit.py, tests/platform_helper/test_command_conduit.py
Addresses https://uktrade.atlassian.net/browse/DBTP-1264
Please add any relevant context for you pull request here, or delete this if none needed.
---
=> chore: DBTP-1264 Add the access type to the log subscription filter name for conduit logs

dbt_platform_helper/commands/conduit.py, tests/platform_helper/test_command_conduit.py
I only needed to change filter name, not log group name, in [this ticket](https://github.com/uktrade/platform-tools/pull/520)
=> fix: correct conduit log group name

dbt_platform_helper/commands/codebase.py, tests/platform_helper/test_command_codebase.py
Addresses [DBTP-1180](https://uktrade.atlassian.net/jira/software/c/projects/DBTP/boards/458?selectedIssue=DBTP-1180)
Not all images were being listed with the platform helper command `codebase list --app <app> --with-images`
This is because boto3 describe_images with the MaxResults parameter set does not guarantee to return the latest images if there are more than MaxResults images available.  [Boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2/client/describe_images.html) strongly recommends using pagination for these types of requests, which is implemented in this change and fixes the problem which was due to the truncated results.
Exisiting test was modified for the paginator implementation and new tests added to cover multiple pages and …
=> fix: DBTP-1180 - list all latest images tagged as commits

dbt_platform_helper/templates/environments/main.tf, tests/platform_helper/test_command_environment.py, tests/platform_helper/utils/test_versioning.py
Addresses [DBTP-1207](https://uktrade.atlassian.net/jira/software/c/projects/DBTP/boards/458?selectedIssue=DBTP-1207).
The terraform extensions module was initially generated with a suffix in its name, `extensions-tf`.  
When the terraform was subsequently regenerated by running the command,
`platform-helper environment generate-terraform --name <env>`
This caused an inconsistency in the generated code and the terraform state because the module name has been changed to `extensions` without a suffix in later terraform-platform-module versions.
We tested this change in the demo-django repo in our own environment.  We applied terraform with the `-tf` suffix on the extensions module name.  We regenerated the terraform using the new command which includes a moved block for the extensions …
=> fix: DBTP-1207 - align extensions module name

dbt_platform_helper/COMMANDS.md, dbt_platform_helper/commands/conduit.py, dbt_platform_helper/commands/copilot.py, dbt_platform_helper/commands/environment.py, dbt_platform_helper/commands/generate.py, dbt_platform_helper/commands/pipeline.py, dbt_platform_helper/commands/version.py, dbt_platform_helper/constants.py, dbt_platform_helper/utils/files.py, dbt_platform_helper/utils/platform_config.py, dbt_platform_helper/utils/validation.py, dbt_platform_helper/utils/versioning.py, platform-config.yml, platform_helper.py, tests/platform_helper/conftest.py, tests/platform_helper/test_command_copilot.py, tests/platform_helper/test_command_environment.py, tests/platform_helper/test_command_generate.py, tests/platform_helper/test_command_pipeline.py, tests/platform_helper/test_command_version.py, tests/platform_helper/test_platform_helper.py, tests/platform_helper/utils/test_files.py, tests/platform_helper/utils/test_platform_config.py, tests/platform_helper/utils/test_validation.py, tests/platform_helper/utils/test_versioning.py
Addresses [DBTP-1153](https://uktrade.atlassian.net/browse/DBTP-1153)
Adds a command `platform-helper version print-desired` which gets the version of platform-helper that the project wants to be installed.
It has an option "--pipeline" which must be one of the configured environment-pipelines which is used to see if the desired version is overridden in the pipeline config. 
The PR also adds in a "versions" parameter to each environment pipeline in the platform-config.yml validation that supports the pipeline-level override.
Version precedence is in this order:
- if the --pipeline option is supplied, the version from the value in `environment_pipelines/<pipeline>/versions/platform-helper` in `platform-config.yml`
- The version from `default_versions/platform-helper` in …
=> feat: Allow override of platform-helper version in regression pipeline

dbt_platform_helper/templates/svc/overrides/cfn.patches.yml, tests/platform_helper/fixtures/make_addons/expected/web/overrides/cfn.patches.yml
Addresses [<link to ticket>](https://uktrade.atlassian.net/browse/DBTP-1154).
This PR adds an additional policy to the service task role so that services can retrieve secrets tagged with `Copilot-application = '__all__'`.
This enables services to read SSM parameters that are global/account wide such as the VPC EGRESS_IP SSM parameter, and the prometheus `/observability/prometheus/adot_config` parameters.
There are two associated PRs to add these tags to global SSM params:
https://github.com/uktrade/terraform-platform-modules/pull/201
https://github.com/uktrade/terraform-module-aws_account/pull/74/
A platform-documentation PR is required - it'll be raised before merging this PR.
---
=> fix: add a policy to allow services to access global SSM parameters

.github/pull_request_template.md, dbt_platform_helper/utils/versioning.py, tests/platform_helper/utils/test_versioning.py
A bug introduced in 10.7.2 meant that the `codebase` commands were failing because it could not find a `platform-config.yml` file. The command is used in the codebase repo, not the deploy repo, so it shouldn't be looking for, or failing because of this file.
Addresses [DBTP-1323](https://uktrade.atlassian.net/browse/DBTP-1323)
---
[DBTP-1323]: https://uktrade.atlassian.net/browse/DBTP-1323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: DBTP-1323 Broken `platform-helper codebase \*` commands

dbt_platform_helper/templates/pipelines/codebase/overrides/stack.ts
So that people are less likely to accidentally end up using images not meant for public consumption.
Tested with `platform-documentation-deploy`.
=> fix: Use tag-latest for ci-image-builder

dbt_platform_helper/templates/pipelines/codebase/overrides/stack.ts, dbt_platform_helper/templates/pipelines/codebase/overrides/types.ts, dbt_platform_helper/utils/validation.py, tests/platform_helper/conftest.py
This is to support building an image from a branch of a deploy repo.
Addresses [DBTP-1001](https://uktrade.atlassian.net/browse/DBTP-1001)
Note no tests for the change in the stack.ts as the javascript files do not currently get tested. (See [DBT-1342](https://uktrade.atlassian.net/browse/DBTP-1342) for details of fixing this)
---
[DBTP-1001]: https://uktrade.atlassian.net/browse/DBTP-1001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: DBTP-1001 Add optional deploy_repository_branch to the codebase pipeline config

dbt_platform_helper/commands/environment.py, tests/platform_helper/test_command_environment.py
Addresses [DBTP-1331](https://uktrade.atlassian.net/browse/DBTP-1331)
The `platform-helper environment generate --name <env>` command retrieves the ARN of a certificate to add into the copilot manifest file. Currently a list of all certificates containing the string of the environment name will be retrieved and the ARN of the first certificate retrieved is used. In the event that there are multiple certificates containing the environment name this may result in the incorrect certificate being added to the manifest.
This PR changes the way that the certificate ARN is retrieved. Rather than querying the certificate store for all certificates that contain the environment name; we now retrieve the certificate ARN from the default certificate that is associated with the HTTPS listener on the …
=> fix: DBTP-1331 Ensure environment generate retrieves correct certificate for load balancer

README.md, images/nginx-dbt-platform/README.md, images/nginx-dbt-platform/entrypoint.sh
Addresses [DBTP-1282](https://uktrade.atlassian.net/browse/DBTP-1282)
Previously setting a PUB_PATH_LIST explicitly to '/' would throw an error when the NGINX container spun up. See ticket for details.
Updated the entrypoint.sh for the image to allow for explicit setting of a PUB_PATH_LIST to '/'
---
[DBTP-1282]: https://uktrade.atlassian.net/browse/DBTP-1282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: DBTP-1282 allow for explicit settings of PUB_PATH_LIST

images/nginx-dbt-platform/README.md, images/nginx-dbt-platform/entrypoint.sh
Addresses [DPM-1231](https://uktrade.atlassian.net/browse/DPM-1231)
One of the services we are migrating uses websockets to manage clashes in edits to forms completed by multiple people. Currently the nginx proxy does not support connection upgrades and this PR introduces support for this along with a refactor for readability.
Tests: no tests currently exist for the nginx container, so I've not added any, though I have tested locally using a docker-compose file which I can commit alongside this PR.
---
[DPM-1231]: https://uktrade.atlassian.net/browse/DPM-1231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(nginx-proxy): support proxying websocket connections

images/copilot-bootstrap/Dockerfile, images/copilot-bootstrap/README.md, images/copilot-bootstrap/ping.xml
Addresses [DPM-1232](https://uktrade.atlassian.net/browse/DPM-1232)
During migration of a service the migration team set up two levels of health check: one in the copilot service configuration and one in pingdom (for the to-be production environment). 
To allow us to shift these checks as far left in the migration process as possible, the boostrap image should respond on the standard path with the normal pingdom custom check XML response.
I've taken the liberty of returning a static response time as this is required by the pingdom check.
---
[DPM-1232]: https://uktrade.atlassian.net/browse/DPM-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(copilot-bootstrap): enable pingdom health checks

dbt_platform_helper/commands/environment.py, regression_tests/pull_request_tests.sh, regression_tests/stages/run_maintenance_page_tests.sh, tests/platform_helper/test_command_environment.py
There can be multiple listener rules with the same name. When we run `online`, we want to delete all of these. Currently only one of each name will be deleted
=> fix: ensure delete_listener_rule deletes multiple rules with same name

.github/workflows/update-documentation.yml
Addresses [DBTP-1083](https://uktrade.atlassian.net/browse/DBTP-1083)
There is a bug in the [update-documentation.yml](https://github.com/uktrade/platform-tools/blob/main/.github/workflows/update-documentation.yml) because currently this workflow gets kicked off only when there's a manual release, and not when there's a release post-merge into main.
[DBTP-1083]: https://uktrade.atlassian.net/browse/DBTP-1083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Addressing workflow bug in DBTP-1083

buildspec.test.yml
We should not be alerted when the tests are targeting someone's individual environment.
---
=> fix: Restrict regression test alerts to toolspr environment

regression_tests/actions/ensure_not_under_maintenance.sh, regression_tests/actions/run_codebase_pipeline.sh, regression_tests/actions/run_demodjango_smoke_tests.sh, regression_tests/actions/run_environment_pipeline.sh, regression_tests/actions/run_maintenance_page_tests.sh, regression_tests/actions/run_platform_helper_environment_generate.sh, regression_tests/actions/run_s3_to_s3_data_migration_tests.sh
Addresses[DBTP-1291]( https://uktrade.atlassian.net/jira/software/c/projects/DBTP/boards/458?selectedIssue=DBTP-1291)
Add the value of the target environment to the echo statements in the various regression tests scripts
---
=> chore: Add TARGET_ENVIRONMENT value to regression tests scripts outputs

regression_tests/buildspecs/stages/build/build-platform-helper-and-reclone-demodjango-repositories-action.yml, regression_tests/buildspecs/stages/deploy/run-codebase-deploy-pipeline.yml, regression_tests/buildspecs/stages/deploy/run-environment-pipeline.yml, regression_tests/buildspecs/stages/test/run-browser-tests.yml, regression_tests/buildspecs/stages/test/run-s3-to-s3-data-migration-tests.yml, regression_tests/src/send_failure_alerts.sh
Addresses [DBTP-1291](https://uktrade.atlassian.net/browse/DBTP-1291)
- Add checks for the targeted repositories being on the main branch before sending a Slack message to alert about any regression test failures.
- Extracted the Slack alert code out into a script.
- Removed `install` phase from buildspec because failures in the install phase do not result in a Slack message alert.
---
[DBTP-1291]: https://uktrade.atlassian.net/browse/DBTP-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: DBTP-1291 Sort out regression test Slack alerts

dbt_platform_helper/utils/aws.py, tests/platform_helper/utils/test_aws.py
Addresses [DBTP-1215](https://uktrade.atlassian.net/browse/DBTP-1215)
We have quite a few errors which can be thrown when there's an issue with the aws_profile, so instead of adding yet another one to the pile I extracted them into a parametarised test and the errors are now clear in the implementation code, and most importantly they are all tested individually
---
[DBTP-1215]: https://uktrade.atlassian.net/browse/DBTP-1215?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: DBTP-1215 Improve error message when AWS profile not set

dbt_platform_helper/utils/aws.py, tests/platform_helper/utils/test_aws.py
Addresses [DBTP-1109](https://uktrade.atlassian.net/browse/DBTP-1109)
This is required to run the database copy command from a pipeline. The way our code gets account id given a profile name is by looking in the users aws config and getting the sso_application_id value from there.
A pipeline will not be configured with SSO, but with assumed roles, so we do not have the sso_account_id. We cannot add that parameter to the aws config in a pipeline as boto sees it and tries to connect via SSO which of course fails.
This workaround allows us to add a new profile_account_id parameter to the aws config file (which is not used by boto and is ignored) from which the command can pick up the account id.
---
[DBTP-1109]: https://uktrade.atlassian.net/browse/DBTP-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
=> feat: Fall back on profile_account_id when trying to match account id to profile name.

README.md
Addresses: The fact we have changed the regression tests pipeline name to end-to-end tests
Please add any relevant context for you pull request here, or delete this if none needed.
---
=> chore: Update README.md to add pull-request-end-to-end-tests

.trufflehogignore, tests/platform_helper/utils/test_aws.py
The fix for [this bug](https://github.com/trufflesecurity/trufflehog/issues/3602) has been released in [Trufflehog 3.83.7](https://github.com/trufflesecurity/trufflehog/releases/tag/v3.83.7).
No actual code changes, so not end to end test run etc.
**Everyone will need to update Trufflehog to avoid annoying and confusing Trufflehog failures.**
---
- ~[ ] Ticket reference included (unless it's a quick out of ticket thing)~
- ~[ ] Includes link(s) to any applicable changes to …
=> ci: Remove tests/platform_helper/utils/test_aws.py from .trufflehogignore

dbt_platform_helper/utils/validation.py, images/copilot-bootstrap/default.conf.template, tests/platform_helper/utils/fixtures/addons_files/alb_addons.yml, tests/platform_helper/utils/fixtures/addons_files/alb_addons_bad_data.yml, tests/platform_helper/utils/test_validation.py
Addresses https://uktrade.atlassian.net/browse/DBTP-1434
Add validation for CDN cache policies in `platform-config.yml`
Related PRs
- https://github.com/uktrade/demodjango-deploy/pull/249
- https://github.com/uktrade/platform-end-to-end-tests/pull/36
---
=> feat: DBTP-1434 - CDN cache policy

dbt_platform_helper/COMMANDS.md, dbt_platform_helper/commands/database.py, dbt_platform_helper/domain/database_copy.py, images/tools/database-copy/entrypoint.sh, tests/platform_helper/domain/test_database_copy.py, tests/platform_helper/test_command_database.py
Addresses https://uktrade.atlassian.net/browse/DBTP-1498
Add option on database dump and load commands to specify the filename of the database dump file.
---
=> fix: DBTP-1498 - Add option for database dump filename

dbt_platform_helper/domain/maintenance_page.py
Addresses [DBTP-1509](https://uktrade.atlassian.net/browse/DBTP-1509)
No tests, just a little text change.
End to end tests run would be pointless for this one.
https://github.com/uktrade/platform-documentation/pull/430 should be merged before this.
---
- ~[ ] [Run the end to end tests for this branch]([https://github.com/uktrade/platform-tools?tab=readme-ov-file#regression-tests](https://github.com/uktrade/platform-end-to-end-tests?tab= …
=> fix: DBTP-1509 Correct link to maintenance pages instructions

dbt_platform_helper/utils/application.py, tests/platform_helper/utils/test_application.py
Addresses [DBTP-1644](https://uktrade.atlassian.net/browse/DBTP-1644)
---
~- If the work includes user interface changes, before and after screenshots included in description~
~- Includes any applicable changes to the documentation in this code base~
~- Includes link(s) to any applicable changes to the documentation in the [DBT Platform Documentation](https://platform.readme.trade.gov.uk/) (can be to a pull request)~
[DBTP-1644]: https://uktrade.atlassian.net/browse/DBTP-1644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: DBTP-1644: handle next token when getting services for application

dbt_platform_helper/domain/copilot_environment.py, dbt_platform_helper/domain/database_copy.py, dbt_platform_helper/providers/vpc.py, tests/platform_helper/domain/test_copilot_environment.py, tests/platform_helper/domain/test_database_copy.py, tests/platform_helper/providers/test_vpc.py, tests/platform_helper/utils/test_aws.py
Addresses [DBTP-1630](https://uktrade.atlassian.net/browse/DBTP-1630)
- removes the session.resource api calls as all information can come from the client and resource will be deprecated
- aligns exception handling
- removes subnet lookup based on route tables
- adds separate attributes for private and public subnets
---
[DBTP-1630]: https://uktrade.atlassian.net/browse/DBTP-1630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: DBTP-1630 - generalise vpc provider

dbt_platform_helper/providers/copilot.py, tests/platform_helper/providers/test_copilot.py
Addresses [DBTP-1645](https://uktrade.atlassian.net/browse/DBTP-1645)
---
- The underlying issue is difficult to replicate in regression pipelines.
[DBTP-1645]: https://uktrade.atlassian.net/browse/DBTP-1645?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: DBTP-1645 - conduit out of memory when querying large data sets

dbt_platform_helper/domain/terraform_environment.py, tests/platform_helper/domain/test_terraform_environment.py, tests/platform_helper/providers/test_config.py
Addresses [DBTP-1630](https://uktrade.atlassian.net/browse/DBTP-1630)
---
[DBTP-1630]: https://uktrade.atlassian.net/browse/DBTP-1630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: DBTP-1630 - remove _fn suffix and variable typo

dbt_platform_helper/domain/maintenance_page.py
Addresses [DBTP-1697](https://uktrade.atlassian.net/browse/DBTP-1697)
No need for an additional test
---
~- [ ] If the work includes user interface changes, before and after screenshots included in description~
~- [ ] Includes any applicable changes to the documentation in this code base~
~- [ ] Includes link(s) to any applicable changes to the documentation in the [DBT Platform Documentation](https://platform.readme.trade.gov.uk/) (can be to a pull request)~
Haven't ran e2e tests but have tested the script on lite prod using a local version of platform helper with these changes (bug does not happen in demo django anyway)
[DBTP-1697]: https://uktrade.atlassian.net/browse/DBTP-1697?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: use get_rules_tag_descriptions method to get descriptions

dbt_platform_helper/domain/config_validator.py, dbt_platform_helper/providers/platform_config_schema.py, tests/platform_helper/providers/test_config.py, tests/platform_helper/utils/fixtures/addons_files/s3_addons.yml, tests/platform_helper/utils/fixtures/addons_files/s3_addons_bad_data.yml
Addresses [DBTP-1635](https://uktrade.atlassian.net/browse/DBTP-1635)
- GREAT service has the requirement of pulling data from multiple S3 source buckets.
- Validation added to support this configuration in a service's `<application>-deploy/platform-config.yml` file
Docs PR: https://github.com/uktrade/platform-documentation/pull/457
---
[DBTP-1635]: https://uktrade.atlassian.net/browse/DBTP-1635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: DBTP-1635 Add additional S3 source bucket validation 

dbt_platform_helper/domain/pipelines.py
Addresses [DBTP-1684](https://uktrade.atlassian.net/browse/DBTP-1684)
[DBTP-1684]: https://uktrade.atlassian.net/browse/DBTP-1684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: DBTP-1684 Pipelines 

dbt_platform_helper/domain/database_copy.py, dbt_platform_helper/providers/load_balancers.py, dbt_platform_helper/providers/vpc.py, tests/platform_helper/domain/test_database_copy.py, tests/platform_helper/providers/test_vpc.py
Addresses [DBTP-1729](https://uktrade.atlassian.net/browse/DBTP-1729)
`environment generate` failed for new environments that don't yet have a copilot service deployed (no copilot security groups).  This change ensures the command works for a new environment without copilot SGs.
In the copilot generate command, the SG should not be needed on the Vpc.  Our `get_vpc` function threw an exception when no matching SGs were found.  This exception has been removed so that Vpc can be returned with security_groups = [].
Handling of the case with no security groups is moved to the database_copy command.  This is the only place where security groups are needed.
A follow up ticket [DBTP-1731](https://uktrade.atlassian.net/browse/DBTP-1731) will look at the VpcProvider and how to separate the `load` …
=> fix: DBPT-1729 - Allows Vpc to be returned without security groups

dbt_platform_helper/domain/maintenance_page.py, tests/platform_helper/domain/test_maintenance_page.py
Addresses [DBTP-1387](https://uktrade.atlassian.net/browse/DBTP-1387)
---
- fix to add host header for each service that is being taken offline
- reduces calls to get host header conditions from 3 to 1 for each service
- improves naming of the `get_host_conditions` to `get_host_header_conditions`
- ~[ ] [Run the end to end tests for this branch]([https://github.com/uktrade/platform-tools?tab=readme-ov-file#regression-tests](https://githu …
=> fix: DBTP-1387 Fix maintenance page offline command when specifiying a specific service

tests/platform_helper/domain/test_terraform_environment.py
Addresses [DBTP-1675](https://uktrade.atlassian.net/browse/DBTP-1675)
test_generate_success added to TestGenerateTerraform using new TerraformManifestProvider
---
~~- [ ] If the work includes user interface changes, before and after screenshots included in description~~
~~- [ ] Includes any applicable changes to the documentation in this code base~~
~~- [ ] Includes link(s) to any applicable changes to the documentation in the [DBT Platform Documentation]~~(https://platform.readme.trade.gov.uk/) (can be to a pull request)
~~- [ ] [Run the end to end tests for this branch]([https://github.com/uktrade/platform-tools?tab=readme-ov-file#regression-tests](https://github.com/uktrade/platform-end-to-end-tests?tab=readme-ov-file#running-the-tests)) and confirm that they are passing~~
[DBTP-1675]: …
=> test: DBTP-1675 Update TestGenerateTerraform with happy path

dbt_platform_helper/providers/files.py, dbt_platform_helper/providers/terraform_manifest.py, tests/platform_helper/providers/test_files.py, tests/platform_helper/providers/test_terraform_manifest.py
Addresses [DBTP-1602](https://uktrade.atlassian.net/browse/DBTP-1602)
Realised during manual testing that because we are moving to JSON formatted env manifests, if a team has an old `main.tf` file either in git or just locally, they will end up with 2 manifests trying to provision the same stuff in their env dir, so terraform apply will fall over. This PR cleans up that file first. 
---
[DBTP-1602]: https://uktrade.atlassian.net/browse/DBTP-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Delete old manifest before creating json one

dbt_platform_helper/providers/files.py, tests/platform_helper/providers/test_files.py
Addresses [DBTP-1784](https://uktrade.atlassian.net/browse/DBTP-1784)
---
[DBTP-1739]: https://uktrade.atlassian.net/browse/DBTP-1739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DBTP-1784]: https://uktrade.atlassian.net/browse/DBTP-1784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: DBTP-1784: Passing a full path as the first mkfile parameter causes a file not found error

dbt_platform_helper/domain/copilot_environment.py, tests/platform_helper/domain/test_copilot_environment.py
Addresses [DBTP-1792](https://uktrade.atlassian.net/browse/DBTP-1792)
---
when running the `platform-helper copilot make-addons` command you will get a `None` type error when trying to call `mkfile` in the `FileProvider`.
[DBTP-1792]: https://uktrade.atlassian.net/browse/DBTP-1792?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: DBTP-1792 Set FileProvider default in CopilotTemplating

dbt_platform_helper/providers/platform_config_schema.py, tests/platform_helper/conftest.py, tests/platform_helper/utils/fixtures/addons_files/s3_policy_addons.yml, tests/platform_helper/utils/fixtures/addons_files/s3_policy_addons_bad_data.yml, tests/platform_helper/utils/test_validation.py
Contributes to [DBTP-1700](https://uktrade.atlassian.net/browse/DBTP-1700).
Because the version `platform-helper` branch specified is not actually used in the environment/codebase pipelines yet, I have run through the environment and codebase deploy commands manually against my environment to check it does not break anything.
---
[End to end test run](https://763451185160-2qjkzelg.eu-west-2.console.aws.amazon.com/codesuite/codepipeline/pipelines/willg-end-to-end-tests/executions/4f7c3844-6616-4e77-bfc9-e5c51a3329e4/visualization?region=eu-west-2).
[DBTP-1700]: https://uktrade.atlassian.net/browse/DBTP-1700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: DBTP-1700 Rationalise S3 policy schema to simplify documentation

tests/platform_helper/domain/test_copilot_environment.py
Out of ticket - fixes an issue where re-running `test_file_provider_default` fails due to not mocking filesystem
---
=> fix: Use fakefs in test to avoid message changing to 'overwritten' in subsequent test runs

copilot/environments/connors-environment/manifest.yml, dbt_platform_helper/providers/platform_config_schema.py, dbt_platform_helper/providers/terraform_manifest.py, tests/platform_helper/providers/test_terraform_manifest.py
Addresses https://uktrade.atlassian.net/browse/DBTP-1789
If no pipeline config is specified use an empty list.
---
=> fix: DBTP-1789 - Default pipelines config to empty list

dbt_platform_helper/commands/generate.py, dbt_platform_helper/commands/version.py, dbt_platform_helper/domain/versioning.py, dbt_platform_helper/providers/platform_helper_versioning.py, dbt_platform_helper/providers/semantic_version.py, dbt_platform_helper/utils/files.py, dbt_platform_helper/utils/versioning.py, tests/platform_helper/domain/test_copilot.py, tests/platform_helper/domain/test_versioning.py, tests/platform_helper/providers/test_semantic_version.py, tests/platform_helper/test_command_generate.py, tests/platform_helper/test_command_secrets.py, tests/platform_helper/utils/test_versioning.py
Addresses [DBTP-1798](https://uktrade.atlassian.net/browse/DBTP-1798)
* Extracted `RequiredVersion` and associated tests from versioning utilities file into its own domain/domain test class
* Updated imports and patch paths
* Convert `VersionStatus` to data class
* Remove duplicated `running_as_installed_package` function and consolidate in `files` utility file
---
[DBTP-1798]: https://uktrade.atlassian.net/browse/DBTP-1798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: DBTP-1798 - move version domain code out of utils

tests/platform_helper/domain/test_copilot.py
Ensures the aws session is mocked for the copilot tests since a call to `get_aws_session_or_abort()` is made at the beginning of the command
---
=> fix: mock aws session in copilot tests

dbt_platform_helper/providers/semantic_version.py, dbt_platform_helper/utils/tool_versioning.py, tests/platform_helper/utils/test_tool_versioning.py
yaml file provider should have been injected into deprecated version file version provider, not directly into PlatformHelperVersioning
I have tested the `config` commands manually however they don't appear in E2E tests, so we will add a test in the next PR.
---
=> fix: config validate command - wrong provider injected into PlatformHelperVersioning

dbt_platform_helper/commands/codebase.py, tests/platform_helper/test_command_codebase.py
Initialising ParameterStore for commands/codebase.py was missed out during [the refactor](https://github.com/uktrade/platform-tools/pull/793), Adding it here to avoid a breaking change.
---
=> fix: Initialise missing parameter provider for codebase commands (off-ticket)

dbt_platform_helper/domain/config.py, dbt_platform_helper/domain/versioning.py, dbt_platform_helper/providers/semantic_version.py, dbt_platform_helper/providers/version.py, dbt_platform_helper/providers/version_status.py, tests/platform_helper/domain/test_config.py, tests/platform_helper/domain/test_versioning.py, tests/platform_helper/providers/test_semantic_version.py, tests/platform_helper/providers/test_version.py, tests/platform_helper/providers/test_version_status.py, tests/platform_helper/test_command_generate.py
Addresses https://uktrade.atlassian.net/browse/DBTP-1895.
- renames AWSVersionProvider and CopilotVersionProvider to AWSVersioning and CopilotVersioning to better align them with the PlatformHelperVersioning class.  
- Moves classes to appropriate files
- Aligns VerisonProvider function names to `get_semantic_version`
---
=> refactor: Improve definition of version classes (DBTP-1895)

dbt_platform_helper/providers/config_validator.py, tests/platform_helper/providers/test_config_validator.py
Relates to https://github.com/uktrade/terraform-platform-modules/pull/370
---
=> fix: From and to account properties no longer required (DBTP-1847)

dbt_platform_helper/providers/version.py, tests/platform_helper/providers/test_version.py
---
When calling via `requests` to github we get Intermittent failures within the end to end tests
- add retry to requests
- on exception log the error and return `None` for the version,  so usage doesn't break.
---
=> fix: Intermittent failures when calling via requests library (off-ticket)

dbt_platform_helper/commands/environment.py, dbt_platform_helper/providers/config_validator.py
Addresses https://uktrade.atlassian.net/browse/DBTP-1888).
Allows (optional) injection of session into the config validator for validations depending on AWS
Addresses TODO to ensure the same session created at the beginning of the command is used for the validations
---
=> refactor: Pass session to config validator (DBTP-1888)

dbt_platform_helper/providers/yaml_file.py, tests/platform_helper/providers/test_yaml_file_provider.py
Fixed issue with missing string quotes for account numbers that start with a 0 thinking they are ints
Addresses https://uktrade.atlassian.net/browse/DBTP-1952
---
=> fix: Removed unnecessary 'null' from empty values in platform-config. (DBTP-1952)

dbt_platform_helper/domain/versioning.py, tests/platform_helper/domain/test_versioning.py
Addresses https://uktrade.atlassian.net/browse/DBTP-2016
Stop validating the config in the version command
---
=> fix: Do not validate config in the version command (DBTP-2016)

tests/platform_helper/domain/test_codebase.py, tests/platform_helper/providers/test_copilot.py, tests/platform_helper/providers/test_ecs.py, tests/platform_helper/providers/test_io.py, tests/platform_helper/providers/test_version.py, tests/platform_helper/test_command_codebase.py, tests/platform_helper/test_command_conduit.py, tests/platform_helper/test_command_copilot.py, tests/platform_helper/test_command_database.py, tests/platform_helper/test_command_environment.py, tests/platform_helper/utils/test_aws.py, tests/platform_helper/utils/test_git.py, tests/utils/test_publish_notifications.py
Off-ticket clean up task.  [Patches should not be defined globally](https://pytest-with-eric.com/mocking/pytest-common-mocking-problems/#Confusing-or-Incorrect-Patch-Targets-Lead-To-False-Positives-or-Brittle-Tests) as this can cause unintended mocking if the patched function or class is called in other tests simultaneously.
---
=> chore: Ensure patches are at module level and not global (off-ticket)

.github/workflows/linting.yml, .github/workflows/unit-tests.yml, .github/workflows/update-documentation.yml
Resolves the following code scanning alert:
If a GitHub Actions job or workflow has no explicit permissions set,
then the repository permissions are used. Repositories created under
organizations inherit the organization permissions. The organizations
or repositories created before February 2023 have the default
permissions set to read-write. Often these permissions do not adhere
to the principle of least privilege and can be reduced to read-only,
leaving the write permission only to a specific types as
`issues: write` or `pull-requests: write`.
---
=> ci: Add explicit permissions on GitHub Actions workflows (off-ticket)

terraform/environment-pipelines/iam.tf
Environment pipeline can't currently deploy the new ECS cluster.
---
- ~[ ] Includes link(s) to any applicable changes to the documentation in the [DBT Platform Documentatio`n](https://platform.readme.trade.gov.uk/) (can be to a pull request)~
=> fix: Add CreateCluster permission (off-ticket)

dbt_platform_helper/utils/aws.py, tests/platform_helper/utils/test_aws.py
Handle missing ssm permission when calling `GetParametersByPath` for data copy, if the environmnet infrastructure (terraform) hasn't been updated.
---
=> fix: Handle missing ssm permission when getting environment details (off-ticket)

dbt_platform_helper/templates/svc/overrides/cfn.patches.yml, tests/platform_helper/fixtures/make_addons/expected/web/overrides/cfn.patches.yml
This is currently performed as a manual step each time Datadog is added into deploy repo files, but is then overwritten again when platform-helper generate command runs.
---
=> fix: Give permission for DataDog process level resource monitoring (DBTP-2238)

terraform/postgres/database-dump/main.tf, terraform/postgres/database-dump/tests/unit.tftest.hcl
Addresses data copy issues when a pipeline has the same source but multiple destinations.
This addresses the following error.
```shell
│ Error: writing IAM Policy Document: duplicate Sid (AllowPipelineAssumeRole). Remove the Sid or ensure the Sid is unique.
│
│   with module.extensions.module.postgres["database"].module.database-dump[0].data.aws_iam_policy_document.assume_ecs_task_role,
│   on .terraform/modules/extensions/terraform/postgres/database-dump/main.tf line 32, in data "aws_iam_policy_document" "assume_ecs_task_role":
│   32: data "aws_iam_policy_document" "assume_ecs_task_role" {
```
---
- ~~[ ] Link to ticket included (unless it's a quick out of ticket thing)~~
- ~~[ ] If the work includes user interface changes, before and after screenshots included in description~~
- ~~[ ] …
=> fix: Allow multiple destination environments for a database copy pipeline (off-ticket)

terraform/extensions/providers.tf
Addresses https://uktrade.atlassian.net/browse/DBTP-2031.
Running `terraform apply` against an account which doesn't match the `allowed_account_ids` results in the error:
Not unit tested as the providers are not testable units, and are mocked in our tests.
The functionality is indirectly tested in our E2E test deployments.
---
=> feat: Constrain environment terraform to only apply in the relevant aws account ID (DBTP-2031)

terraform/codebase-pipelines/buildspec-deploy.yml
Addresses https://uktrade.atlassian.net/browse/DBTP-2311
- Ensure pipeline stage exits with deploy command exit code
---
=> fix: False success from pipeline after failed deployment (DBTP-2311)

dbt_platform_helper/entities/platform_config_schema.py, terraform/postgres/rds.tf, terraform/postgres/tests/unit.tftest.hcl, terraform/postgres/variables.tf, tests/platform_helper/utils/fixtures/addons_files/postgres_addons.yml, tests/platform_helper/utils/fixtures/addons_files/postgres_addons_bad_data.yml, tests/platform_helper/utils/test_validation.py
Allows a team to apply a Postgres change immediately as opposed to during the maintenance window.
See also:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#apply_immediately-1
Addresses [DBTP-2351](https://uktrade.atlassian.net/browse/DBTP-2351).
---
https://763451185160-zptr46bd.eu-west-2.console.aws.amazon.com/codesuite/codepipeline/pipelines/pull-request-end-to-end-tests/executions/ad9fbde4-d95d-4f1c-8bbd-49315cdbfa98/visualization?region=eu-west-2
[DBTP-2351]: https://uktrade.atlassian.net/browse/DBTP-2351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add `apply_immediately` PostgreSQL configuration (DBTP-2351)
