README.md, domain-bootstrap.py
initial working code for domain bootstrap
=> Certificates domains

domain-bootstrap.py
New feature to automate the R53 update with Load balancer record
=> auto update LB feature

code-deploy-bootstrap.py, templates/put-codebuild-role-policy.json
added ability to send slack message when image is built.
=> add slack to aws parameter store

copilot-bootstrap.py, migration-tools/README.md, migration-tools/ci-conf.yaml, migration-tools/combine-ci-paas-config.py, migration-tools/full-config.yaml, migration-tools/get-ci-conf.py, migration-tools/get-paas-config.py, migration-tools/main.py, migration-tools/paas-conf.yaml, migration-tools/requirements.txt, templates/env/addons/password-opensearch.yml, templates/instructions.txt, templates/svc/manifest-backend.yml, templates/svc/manifest-public.yml
Remove command key from manifest.yml
Re-enable IP filter in manifest
Add migration-tools directory with code and config to generate the bootstrap files
=> Update copilot-bootstrap make-config to reflect changes

storage-plans.yaml
Defining sizing according to current CF/PaaS specifications
=> Configuring T-Shirt sizing for Redis and OS

code-deploy-bootstrap.py, domain-bootstrap.py
This change is for when we have multiple environments.
=> Remove r53 records

.pre-commit-config.yaml, commands/bootstrap_cli.py, commands/codebuild_cli.py, commands/copilot_cli.py, commands/dns_cli.py, commands/utils.py, migration-tools/build-copilot-config.py, migration-tools/combine-ci-paas-config.py, migration-tools/get-ci-config.py, migration-tools/get-paas-config.py, pyproject.toml, requirements-test.in, requirements-test.txt, tests/test_storage_validation.py, utils/aws.py
- Add `pre-commit` hooks:
- `black` as code formatter.
- `pre-commit-hooks` for replacing line endings and detecting private keys. 
- `pytest` for running tests.
- Apply initial `pre-commit` changes for all files.
- The `pre-commit` hooks are only run on the files that are changed.
JIRA ticket: https://uktrade.atlassian.net/browse/GPM-534
=> Add `pre-commit` hooks

commands/dns_cli.py, utils/aws.py
PR to improve tryling of user interaction on cli
=> formatting on dns_cli

pyproject.toml
- Add description so it shows up properly in the PyPi index.
PyPi project - https://pypi.org/project/dbt-copilot-tools/
=> Add description in `poetry` configuration

pyproject.toml
- Update the script/command so it is shorter and easier to type
=> Update `script`/command in `pyproject.toml`

README.md
- Add `Dockerfile.test` documentation
- Add what DBT stands for
=> Add `Dockerfile.test` documentation

.pre-commit-config.yaml, buildspec.test.yml, templates/addons/env/rds-postgres.yml
=> Add check-cloudformation to precommit/CodeBuild and correct rds-postgres template

.pre-commit-config.yaml
- Update `pre-commit` configuration to check for tracked file changes as a result of `pre-commit` hooks
- Stash all changes, check if there are any changes, remove stashed state.
- Update order of `pre-commit` hooks
- Remove stashed state at the end of the `pre-commit` workflow.
=> Update `pre-commit` configuration to check file changes

commands/COMMANDS.md, commands/bootstrap_cli.py, commands/check_cloudformation.py, tests/test_bootstrap_cli.py
Part of https://uktrade.atlassian.net/browse/DBTP-305
This is 1 of a few.
=> DBTP-305 Hardcode the location of bootstrap.yml

commands/COMMANDS.md, commands/check_cloudformation.py, commands/copilot_cli.py, tests/test_copilot_cli.py
- Remove `storage_config_file` option
JIRA ticket - https://uktrade.atlassian.net/browse/DBTP-305
=> DBTP 305 -  Remove storage option

.pre-commit-config.yaml
- Remove test `pre-commit` hook
=> Remove running tests from `pre-commit` configuration

README.md, poetry.lock
- Update CodeBuild project build badge
- The CodeBuild project is now managed via Terraform, whereas it was created manually before.
=> Update CodeBuild project build badge

commands/utils.py, tests/test_bootstrap_cli.py, tests/test_utils.py
I got this error and I had no idea what it meant to me, so I made it a little more informative.
=> Make AWS profile not configured error more helpful

commands/conduit_cli.py, tests/test_conduit_cli.py
https://uktrade.atlassian.net/browse/DBTP-340
=> DBPT-340 Use shared Docker image(s)

commands/dns_cli.py, commands/waf_cli.py, pyproject.toml, tests/conftest.py, tests/test_dns_cli.py, tests/test_waf_cli.py
To satisfy https://uktrade.atlassian.net/browse/DBTP-343
See comments inline.
=> DBTP-343 Handle hyphens in application names when getting Elastic Load Balancer details

commands/COMMANDS.md, commands/bootstrap_cli.py, commands/utils.py, pyproject.toml, tests/fixtures/newenv_environment_manifest.yml, tests/test_bootstrap_cli.py, tests/test_utils.py
- Add `copy-secrets` command to copy from one environment to a new environment
- Update Commands Reference documentation
- Update version from `0.1.12` -> `0.1.13`
Jira ticket - https://uktrade.atlassian.net/browse/DBTP-342
=> Add `copy-secrets` command

poetry.lock, pyproject.toml
Fixing this security vulnerability https://github.com/uktrade/copilot-tools/security/dependabot/6
=> add cryptography^41.0.3

commands/bootstrap_cli.py, commands/codebuild_cli.py, commands/conduit_cli.py, commands/copilot_cli.py, commands/dns_cli.py, commands/utils.py, commands/waf_cli.py, copilot_helper.py, migration-tools/build-copilot-config.py, migration-tools/get-ci-config.py, migration-tools/get-paas-config.py, pyproject.toml, tests/conftest.py, tests/test_addons_validation.py, tests/test_bootstrap_cli.py, tests/test_check_cloudformation.py, tests/test_codebuild_cli.py, tests/test_conduit_cli.py, tests/test_copilot_cli.py, tests/test_create_command_docs.py, tests/test_dns_cli.py, tests/test_utils.py, tests/test_waf_cli.py, tests/utils/fixtures/pyproject.toml, tests/utils/fixtures/pyproject_malformed.toml, tests/utils/fixtures/pyproject_no_version.toml, tests/utils/test_check_pypi.py, utils/check_pypi.py
To adhere to our newly agreed DBT PaaS Code Style Guide.
The human changes are in [this commit](https://github.com/uktrade/copilot-tools/pull/148/commits/1af4547687d59fa2b5f34459d3163b55a9fa235a). The rest is just automatic formatting.
=> Change max line length to 100

commands/templates/addons/env/opensearch.yml, pyproject.toml, tests/fixtures/make_addons/expected/environments/addons/my-opensearch.yml
Minor issue encountered when completing https://uktrade.atlassian.net/browse/DBTP-403
=> Fix opensearch secret name and description

commands/templates/svc/manifest-public.yml, pyproject.toml, tests/fixtures/test_service_manifest.yml
EMAIL variable was required for the ipfilter sidecar. This PR adds it.
=> Added EMAIL variable to the ipfilter sidecar

commands/templates/addons/env/aurora-postgres.yml, commands/templates/addons/env/rds-postgres.yml, pyproject.toml, tests/fixtures/make_addons/expected/environments/addons/my-aurora-db.yml, tests/fixtures/make_addons/expected/environments/addons/my-rds-db.yml
- ddl query logging for PostgreSQL
- ddl query logging for Aurora PostgreSQL
- Some template tidy ups to add more prefixed names to resources
=> DBTP-429: query logging for postgres

dbt_copilot_helper/templates/svc/manifest-public.yml, pyproject.toml, tests/fixtures/test_service_manifest.yml
- Bump up the default grace period from 90s -> 180s
=> DBTP-439 - Update default grace period

pyproject.toml
I forgot to do it in the last one.
=> DBTP-472 Bump version

buildspec.yml, pyproject.toml
Fixes typo in [this PR](https://github.com/uktrade/copilot-tools/pull/195)
=> DBTP-430 Update Paketo builder and run images (pt 2)

dbt_copilot_helper/templates/addons/env/redis-cluster.yml, dbt_copilot_helper/templates/env/overrides/cfn.patches.yml, pyproject.toml, tests/fixtures/make_addons/expected/environments/addons/my-redis.yml, tests/fixtures/make_addons/expected/environments/overrides/cfn.patches.yml
- Add engine and slow logs to cloudwatch
- Add log delivery to environment level cloudwatch logs resource policy
- Restrict source account for opensearch logs
=> DBTP-526 Redis logging

dbt_copilot_helper/commands/copilot.py, dbt_copilot_helper/templates/addons/env/s3.yml, dbt_copilot_helper/templates/addons/svc/s3-policy.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-s3-bucket-with-an-object.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-s3-bucket.yml, tests/copilot_helper/fixtures/make_addons/expected/web/addons/my-s3-bucket-bucket-access.yml, tests/copilot_helper/fixtures/make_addons/expected/web/addons/my-s3-bucket-with-an-object.yml, tests/copilot_helper/fixtures/make_addons/expected/web/addons/my-s3-bucket.yml
Addresses https://uktrade.atlassian.net/browse/DBTP-548
=> DBTP-548 Fix KMS key reference in S3 policy

dbt_copilot_helper/schemas/addons-schema.json
To avoid large diffs in pull requests going forward.
=> Use 2 space for indenting and consistent formatting in addons-schema.json

dbt_copilot_helper/commands/pipeline.py, dbt_copilot_helper/templates/pipelines/codebase/overrides/stack.ts, pyproject.toml
- Add information about the pipeline to parameter store for use by other tools
- Use glob to ignore node_modules directory if present
=> DBTP-464 add pipeline codebase config

dbt_copilot_helper/templates/pipelines/codebase/overrides/stack.ts
To make it easier to pull a list of all codebases and their pipelines for a given application.
=> DBTP-464 Namespace pipelines with the application name

dbt_copilot_helper/commands/copilot.py, dbt_copilot_helper/templates/addons/env/aurora-postgres.yml, dbt_copilot_helper/templates/addons/env/monitoring.yml, dbt_copilot_helper/templates/addons/env/opensearch.yml, dbt_copilot_helper/templates/addons/env/rds-postgres.yml, dbt_copilot_helper/templates/addons/env/redis-cluster.yml, dbt_copilot_helper/templates/addons/env/s3.yml, dbt_copilot_helper/templates/addons/svc/s3-policy.yml
Because it's been bugging me for for a while.
No need to publish this one, it doesn't actually change the behaviour of `copilot-helper`, just helps make the code make more sense.
=> Rename `service` to `addon_config` in the addon templates

addons-example.yml
I realised I have been making changes without making the corresponding updates in the documentation.
=> DBTP-559 Update addons.example.yml with S3 deletion-policy

addons-example.yml, dbt_copilot_helper/schemas/addons-schema.json, dbt_copilot_helper/templates/addons/env/aurora-postgres.yml, dbt_copilot_helper/templates/addons/env/opensearch.yml, dbt_copilot_helper/templates/addons/env/rds-postgres.yml, dbt_copilot_helper/templates/addons/env/redis-cluster.yml, pyproject.toml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-aurora-db.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-opensearch-longer.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-opensearch.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-rds-db.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-redis.yml, tests/copilot_helper/test_command_copilot.py
- Add `DeletionPolicy` and `UpdateReplacePolicy` to:
- rds-postgres
- aurora-postgres
- opensearch
- redis
=> DBTP-591 - Prevent resources being deleted by CloudFormation

dbt_copilot_helper/commands/dns.py, pyproject.toml, tests/copilot_helper/test_command_dns.py
Introduced during refactoring work in DBTP-444. Test added around this case.
=> Fixed a bug where hosted zones were created multiple times

dbt_copilot_helper/commands/conduit.py, pyproject.toml, tests/copilot_helper/test_command_conduit.py
Add subscription filters to the conduit session log groups
=> DBTP-600 - Add conduit log subscription filters

dbt_copilot_helper/templates/pipelines/environments/buildspec.yml, pyproject.toml, tests/copilot_helper/expected_files/pipeline/pipelines/environments/buildspec.yml
So we avoid the downgrade errors in ci.
=> Bump copilot cli version in generated templates

dbt_copilot_helper/schemas/addons-schema.json, dbt_copilot_helper/templates/addons/env/rds-postgres.yml, pyproject.toml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-rds-db.yml, tests/copilot_helper/fixtures/make_addons/rds_addons.yml
Adds in logic to the templates to support restoring a snapshot DB to RDS postgres
=> DBTP-575 Add snapshot ability to the RDS Postgres addon

addons-example.yml, dbt_copilot_helper/schemas/addons-schema.json, dbt_copilot_helper/templates/addons/env/aurora-postgres.yml, dbt_copilot_helper/templates/addons/env/rds-postgres.yml, pyproject.toml, tests/copilot_helper/fixtures/make_addons/aurora_addons.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-aurora-db.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-rds-db.yml
- Add deletion-protection property for aurora and rds postgres addons
=> DBTP-659 - Add deletion-protection property to copilot-tools

dbt_copilot_helper/commands/copilot.py, pyproject.toml
- Don't display full stack trace on addons.yml validation error
=> DBTP-644 - Improve validation error

dbt_copilot_helper/commands/codebase.py, dbt_copilot_helper/commands/copilot.py, dbt_copilot_helper/commands/dns.py, dbt_copilot_helper/commands/svc.py, dbt_copilot_helper/commands/waf.py, dbt_copilot_helper/utils/application.py, dbt_copilot_helper/utils/aws.py, pyproject.toml, tests/copilot_helper/conftest.py, tests/copilot_helper/test_command_codebase.py, tests/copilot_helper/test_command_copilot.py, tests/copilot_helper/test_command_dns.py, tests/copilot_helper/test_command_pipeline.py, tests/copilot_helper/test_command_svc.py, tests/copilot_helper/test_command_waf.py, tests/copilot_helper/utils/test_application.py, tests/copilot_helper/utils/test_aws.py
Use the get_aws_session_or_abort function in the aws module in preference to the raw boto3.client call to get better errors if not logged in.
=> DBTP-509 Use better error handling for copilot-helper

dbt_copilot_helper/utils/application.py, pyproject.toml
Set recursive option to false when retrieving the environments from the parameter store
=> DBTP-733 - Error retrieving environments from param store

Dockerfile.debian
To support @WillGibson and @samuele-mattiuzzo's work on https://uktrade.atlassian.net/browse/DBTP-681
=> Install jq, unzip and AWS CLI

dbt_copilot_helper/COMMANDS.md, dbt_copilot_helper/commands/codebase.py, pyproject.toml
Small change following [discussion here](https://github.com/uktrade/platform-documentation/pull/149#discussion_r1486504749)
=> update help text for --codebase flag

.envrc.sample
Because the account was renamed and we all need to get on board with it ;-)
=> Change AWS_PROFILE in .envrc.sample to platform-tools

.pre-commit-config.yaml, dbt_copilot_helper/commands/bootstrap.py, dbt_copilot_helper/commands/config.py, dbt_copilot_helper/commands/dns.py, dbt_copilot_helper/utils/validation.py, migration-tools/build-copilot-config.py, tests/copilot_helper/test_command_application.py, tests/copilot_helper/test_copilot_helper.py
To keep some noise out of the pull request that coming next.
=> Run black formatting on all files

dbt_copilot_helper/templates/addons/env/opensearch.yml, pyproject.toml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-opensearch-longer.yml, tests/copilot_helper/fixtures/make_addons/expected/environments/addons/my-opensearch.yml
https://uktrade.atlassian.net/browse/DBTP-781
Slack discussion / context [here](https://ditdigitalteam.slack.com/archives/C046VC4HTKN/p1709126769784399)
=> fix: ensure opensearch domain is created before param

.github/workflows/pull-request-checks.yml, .github/workflows/quality-checks.yml
Because it's too easy to forget.
Pull request to fix the Node.js@16 deprecation warning: https://github.com/ytanikin/PRConventionalCommits/pull/6
=> ci: Add pull request title validation

tests/copilot_helper/test_command_copilot.py
Co-authored by @antroy-madetech
=> fix: attempt to fix expected vs actual issue

dbt_platform_helper/templates/pipelines/environments/buildspec.yml, tests/platform_helper/expected_files/pipeline/pipelines/environments/buildspec.yml
Inconsistent variable name after rename
=> fix: Fix renaming capitalisation

README.md, dbt_platform_helper/README.md
Noticed a few links were broken in the documentation
=> fix: Fix broken links in ReadMe files

buildspec.pypi.yml
=> fix: Restore yml map type

tests/platform_helper/utils/fixtures/addons_files/no_param_addons.yml, tests/platform_helper/utils/fixtures/addons_files/no_param_addons_bad_data.yml, tests/platform_helper/utils/fixtures/addons_files/opensearch_addons.yml, tests/platform_helper/utils/fixtures/addons_files/opensearch_addons_bad_data.yml, tests/platform_helper/utils/fixtures/addons_files/postgres_addons.yml, tests/platform_helper/utils/fixtures/addons_files/postgres_addons_bad_data.yml, tests/platform_helper/utils/fixtures/addons_files/redis_addons.yml, tests/platform_helper/utils/fixtures/addons_files/redis_addons_bad_data.yml, tests/platform_helper/utils/fixtures/addons_files/s3_addons.yml, tests/platform_helper/utils/fixtures/addons_files/s3_addons_bad_data.yml, tests/platform_helper/utils/test_validation.py
The TF work resulted in a number of new configuration options - these had been added but lacked unit tests.
=> chore: Add validation tests for new extension attributes

dbt_platform_helper/commands/copilot.py
- Add check that the current environment was in the list of copilot environments
- Create bucket name from environment in config and add it to kms key alias
=> fix: Update get_s3_kms_alias_arns to check for environment name

dbt_platform_helper/commands/copilot.py
=> chore: DBTP-1016 Refactor get_s3_kms_alias_arns method

dbt_platform_helper/templates/svc/maintenance_pages/dmas-migration.html, tests/platform_helper/test_command_environment.py
Maintenance template added for DMAS migration based on wording provided by the service team.
=> chore: Add DMAS migration maintenance template

.github/workflows/create-release.yml
See https://github.com/google-github-actions/release-please-action?tab=readme-ov-file#migration
=> ci: change to non-deprecated github action for release-please

regression_tests/stages/run_environment_pipeline.sh
Now we are able to configure the `toolspr` environment pipeline without hacking, let's do it properly.
---
=> chore: DBTP-681 Use proper toolspr environment pipeline in regression tests

images/conduit/postgres/Dockerfile
Addresses https://uktrade.atlassian.net/browse/DBTP-1093
---
=> fix: DBTP-1093 - Add postgres version 16 to conduit image

poetry.lock, pyproject.toml
Addresses https://uktrade.atlassian.net/browse/DBTP-274
Please add any relevant context for you pull request here, or delete this if none needed.
---
- [/] Scope included as per [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)
- [/] Ticket reference included (unless it's a quick out of ticket thing)
- [/] Link to ticket included (unless it's a quick out of ticket thing)
=> chore: upgrade cfn-lint

regression_tests/stages/run_demodjango_smoke_tests.sh
Goes with changes @gabelton is making.
https://github.com/uktrade/demodjango/pull/82
---
=> test: Update run_demodjango_smoke_tests.sh

dbt_platform_helper/README.md
It was out of date and wrong.
Tests not applicable.
---
=> docs: Correct introductory paragraph on the Platform Helper README.md

buildspec.test.yml, regression_tests/pull_request_tests.sh, regression_tests/stages/build_platform_helper.sh, regression_tests/stages/clone_demodjango.sh, regression_tests/stages/clone_demodjango_deploy.sh, regression_tests/stages/ensure_not_under_maintenance.sh, regression_tests/stages/run_codebase_pipeline.sh, regression_tests/stages/run_demodjango_smoke_tests.sh, regression_tests/stages/run_environment_pipeline.sh, regression_tests/stages/run_maintenance_page_tests.sh, regression_tests/stages/run_platform_helper_environment_generate.sh, regression_tests/stages/run_platform_helper_generate.sh, regression_tests/stages/set_up_aws_config.sh, regression_tests/stages/set_up_git_config.sh
So it's more obvious what the tests are doing if they fail.
Also standardised line breaks and where we put this in the steps.
No additional tests obviously.
---
=> test: Add more regression test narrative

dbt_platform_helper/templates/pipelines/codebase/overrides/stack.ts
Addresses [[DBTP-1392 Codebase pipelines will not deploy](https://uktrade.atlassian.net/browse/DBTP-1392)
No tests because the file in question is not tested and depending on the outcome of a spike in play, we may be removing it soon anyway.
The changes have been thoroughly manually tested under https://github.com/uktrade/orp-deploy/pull/6.
---
=> fix: DBTP-1392 Allow codebase pipelines to codestar-connections:GetConnectionToken

regression_tests/actions/run_maintenance_page_tests.sh
Small typo in regression tests script output
---
=> fix: fix typo

regression_tests/actions/run_demodjango_smoke_tests.sh, regression_tests/actions/run_s3_to_s3_data_migration_tests.sh, regression_tests/actions/set_up_aws_config.sh
Addresses [DBTP-1291](https://uktrade.atlassian.net/browse/DBTP-1291)
We changed the role name and forgot it is used here in the other repository.
---
[DBTP-1291]: https://uktrade.atlassian.net/browse/DBTP-1291?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: DBTP-1291 Update regression tests role

dbt_platform_helper/commands/database_helpers.py
Addresses [DBTP-1109](https://uktrade.atlassian.net/browse/DBTP-1109)
Just an update, tests may need to be resolved, goes hand in hand with https://github.com/uktrade/terraform-platform-modules/pull/244
---
[DBTP-1109]: https://uktrade.atlassian.net/browse/DBTP-1109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: make bucket and task names non-clashing

CHANGELOG.md
It's worth making this obvious for people looking at the change log and releases (already updated) to see if they will help them a problem they are seeing.
---
- ~[ ] Ticket reference included (unless it's a quick out of ticket thing)~
- ~[ ] [Trigger the pull request regression tests for this …
=> docs: Call out the offline command fix in the changelog

README.md
Addresses [[DBTP-1511](https://uktrade.atlassian.net/browse/DBTP-1511)](https://uktrade.atlassian.net/browse/[DBTP-1511](https://uktrade.atlassian.net/browse/DBTP-1511))
Afterthought. No changes to code or tests.
---
- ~[ ] [Trigger the pull request regression tests for this branch](https://github.com/uktrade/platform-tools?tab=readme-ov-file#regression-tests) and confirm that they are passing~
[DBTP-1511]: https://uktrade.atlassian.net/browse/DBTP-1511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
=> docs: DBTP-1511 Link to Codecov in unit tests section of README

dbt_platform_helper/COMMANDS.md, dbt_platform_helper/commands/version.py, tests/platform_helper/test_command_version.py
Addresses [DBTP-1534](https://uktrade.atlassian.net/browse/DBTP-1534)
Please add any relevant context for you pull request here, or delete this if none needed.
---
[DBTP-1534]: https://uktrade.atlassian.net/browse/DBTP-1534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: DBTP-1534 - Removed autocompletion for the version get-platform-helper-for-project

codecov.yml
Follow on from [DBTP-1511](https://uktrade.atlassian.net/browse/DBTP-DBTP-1511)
Can be seen in action at: https://app.codecov.io/github/uktrade/platform-tools/tree/DBTP-1511-exclude-test-files-from-codecov/tests, but we may need to erase the existing data to get risd of the metrics which include the test files. Time will tell.
---
- ~[ ] [Trigger the pull request regression …
=> ci: DBTP-1511 Exclude test files from Codecov checks

.github/pull_request_template.md
I noticed it was wrong.
---
- ~[ ] Ticket reference included (unless it's a quick out of ticket thing)~
- ~[ ] [Trigger the pull request regression tests for this branch](https://github.com/uktrade/platform-tools?tab=readme-ov-file#regression-tests) and confirm that they are passing~
=> chore: Correct the end to end test checklist item

dbt_platform_helper/domain/conduit.py, tests/platform_helper/domain/test_conduit.py
Addresses [DBTP-1520](https://uktrade.atlassian.net/browse/DBTP-1520)
---
[DBTP-1520]: https://uktrade.atlassian.net/browse/DBTP-1520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: Fixed method parameter reference

dbt_platform_helper/commands/application.py
=> chore: Add some context to why we cannot get rid of the application commands yet

dbt_platform_helper/domain/conduit.py, dbt_platform_helper/exceptions.py, dbt_platform_helper/providers/copilot.py, dbt_platform_helper/providers/ecs.py, tests/platform_helper/domain/test_conduit.py, tests/platform_helper/providers/test_copilot.py, tests/platform_helper/providers/test_ecs.py
Addresses [DBTP-1577](https://uktrade.atlassian.net/browse/DBTP-1577)
---
[DBTP-1577]: https://uktrade.atlassian.net/browse/DBTP-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: DBTP-1577 Fix conduit (ecs) exec race condition 

dbt_platform_helper/commands/codebase.py, dbt_platform_helper/commands/conduit.py, dbt_platform_helper/commands/secrets.py, dbt_platform_helper/domain/codebase.py, dbt_platform_helper/providers/cloudformation.py, dbt_platform_helper/providers/copilot.py, dbt_platform_helper/providers/ecs.py, dbt_platform_helper/templates/pipelines/environments/manifest.yml, images/debian-python/Dockerfile.debian, tests/platform_helper/domain/test_codebase.py, tests/platform_helper/providers/test_copilot.py
No code changes, nothing to worry about in this.
=> chore: Squad2 todo updates

dbt_platform_helper/providers/ecs.py, images/debian-python/Dockerfile.debian
It was something @tony-griffin and I did for the end to end tests, but we didn't use this image in the end, so it's just bloat.
Off ticket. No tests for this. I will republish the image if folk approve.
---
- ~[ ] Ticket reference included (unless it's a quick out of ticket thing)~
- ~[ ] [Run the end …
=> chore!: Don't install poetry in Dockerfile.debian

dbt_platform_helper/domain/codebase.py, dbt_platform_helper/utils/aws.py, tests/platform_helper/domain/test_codebase.py, tests/platform_helper/utils/test_aws.py
=> fix: Fixing json loads

dbt_platform_helper/commands/codebase.py, dbt_platform_helper/commands/conduit.py, dbt_platform_helper/commands/secrets.py, dbt_platform_helper/domain/codebase.py, dbt_platform_helper/domain/conduit.py, dbt_platform_helper/exceptions.py, dbt_platform_helper/providers/cloudformation.py, dbt_platform_helper/providers/copilot.py, dbt_platform_helper/providers/ecs.py, dbt_platform_helper/providers/secrets.py, dbt_platform_helper/utils/application.py, dbt_platform_helper/utils/aws.py, tests/platform_helper/domain/test_codebase.py, tests/platform_helper/domain/test_conduit.py, tests/platform_helper/domain/test_database_copy.py, tests/platform_helper/providers/test_cloudformation.py, tests/platform_helper/providers/test_copilot.py, tests/platform_helper/providers/test_ecs.py, tests/platform_helper/providers/test_secrets.py, tests/platform_helper/test_command_codebase.py, tests/platform_helper/test_command_conduit.py, tests/platform_helper/test_exceptions.py
Addresses [DBTP-1520](https://uktrade.atlassian.net/browse/DBTP-1520)
Replay after @WillGibson got too excited by the big green button in GitHub and merged before the end to end tests were run. 
---
[DBTP-1520]: https://uktrade.atlassian.net/browse/DBTP-1520?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: DBTP-1520 Improving provider structure and exception handling (2nd pass)

dbt_platform_helper/domain/codebase.py, dbt_platform_helper/domain/conduit.py, dbt_platform_helper/domain/database_copy.py, dbt_platform_helper/providers/copilot.py, dbt_platform_helper/utils/aws.py, dbt_platform_helper/utils/validation.py, tests/platform_helper/domain/test_codebase.py, tests/platform_helper/domain/test_conduit.py, tests/platform_helper/domain/test_database_copy.py, tests/platform_helper/providers/test_copilot.py, tests/platform_helper/utils/test_aws.py, tests/platform_helper/utils/test_validation.py, tests/utils/test_check_pypi.py, utils/check_pypi.py
Addresses [DBTP-1585](https://uktrade.atlassian.net/browse/DBTP-1585)
---
[DBTP-1585]: https://uktrade.atlassian.net/browse/DBTP-1585?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: DBTP-1585 Drop the _fn suffix from class variable names

dbt_platform_helper/domain/conduit.py, dbt_platform_helper/providers/copilot.py, tests/platform_helper/domain/test_conduit.py, tests/platform_helper/providers/test_copilot.py
Quick pass over the refactored code.
Picked off unused imports, unused clients etc...
Unit tests are passing - e2e test running:
https://eu-west-2.console.aws.amazon.com/codesuite/codepipeline/pipelines/pull-request-end-to-end-tests/executions/bcd8ba93-62fc-4314-be10-37c8f17b5821/visualization?region=eu-west-2
---
=> refactor: Remove some unused imports and variables

dbt_platform_helper/providers/platform_config_schema.py
=> fix: DBTP-1605 checking new param

dbt_platform_helper/providers/platform_config_schema.py
=> fix: DBTP-1605 adding new key for parameter

tests/platform_helper/fixtures/make_addons/s3_addons.yml, tests/platform_helper/utils/fixtures/addons_files/s3_policy_addons_bad_data.yml, tests/platform_helper/utils/test_validation.py
Addresses [DBTP-1605](https://uktrade.atlassian.net/browse/DBTP-1605)
---
[DBTP-1605]: https://uktrade.atlassian.net/browse/DBTP-1605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test: DBTP-1605 tests for new fields

tests/platform_helper/domain/test_codebase.py
=> refactor: DBTP-1451 Addressed tests

dbt_platform_helper/domain/database_copy.py, dbt_platform_helper/providers/vpc.py, dbt_platform_helper/utils/application.py, dbt_platform_helper/utils/aws.py, tests/platform_helper/domain/test_database_copy.py, tests/platform_helper/providers/test_vpc.py, tests/platform_helper/utils/test_aws.py
=> refactor: Refactoring VPC provider

dbt_platform_helper/commands/copilot.py, tests/platform_helper/test_command_copilot.py
Bug introduced during a merge conflict resolution in the previous PR.
Test made better to prevent the bug reappearing.
---
=> fix: for the bug introduced during merging a conflict in the previous PR

dbt_platform_helper/domain/maintenance_page.py
=> refactor: DBTP-1678 maintenance page domain refactor

dbt_platform_helper/domain/maintenance_page.py
Reverts uktrade/platform-tools#717
=> refactor: "refactor: DBTP-1678 maintenance page domain refactor"

dbt_platform_helper/templates/pipelines/codebase/overrides/package-lock.json, poetry.lock, pyproject.toml
- Update dependencies for copilot pipelines
- Update Jinja2 to 3.1.5
---
=> chore: Fix dependabot alerts

dbt_platform_helper/domain/copilot_environment.py
Inject IO provider into CopilotTemplating class instead of calling click from provider.
---
=> chore: Inject IO provider into CopilotTemplating

dbt_platform_helper/COMMANDS.md, dbt_platform_helper/commands/config.py, dbt_platform_helper/providers/semantic_version.py, dbt_platform_helper/utils/versioning.py, tests/platform_helper/conftest.py, tests/platform_helper/providers/test_semantic_version.py, tests/platform_helper/test_command_config.py, tests/platform_helper/test_command_generate.py, tests/platform_helper/utils/test_versioning.py
Addresses [DBTP-1766](https://uktrade.atlassian.net/browse/DBTP-<ticket>)
---
[DBTP-1766]: https://uktrade.atlassian.net/browse/DBTP-1766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: DBTP-1766 consolidate versions class

copilot/environments/connors-environment/manifest.yml, dbt_platform_helper/utils/versioning.py, tests/platform_helper/utils/test_versioning.py
Addresses [DBTP-1767](https://uktrade.atlassian.net/browse/DBTP-1767)
[DBTP-1767]: https://uktrade.atlassian.net/browse/DBTP-1767?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: DBTP-1767 - IO provider injected across version

dbt_platform_helper/providers/terraform_manifest.py, tests/platform_helper/providers/test_terraform_manifest.py
Addresses https://uktrade.atlassian.net/browse/DBTP-1896
Related PRs
- https://github.com/uktrade/terraform-platform-modules/pull/363
- https://github.com/uktrade/platform-documentation/pull/544
---
=> feat: Add deploy repository branch to pipeline generate (DBTP-1896)

CONTRIBUTING.md, README.md
Because some people want to contribute and that's good, but needs a bit of coordinating.
---
=> docs: Add initial contributing guidelines (off-ticket)

CONTRIBUTING.md
Missed @JohnStainsby's suggestion before I smashed the merge button in previous pull requests
---
=> docs: Correct typo in CONTRIBUTING.md (off-ticket)

.github/workflows/unit-tests.yml
Address `Commit creating failed: {"message":"Token required because branch is protected"}` errors like [this](https://github.com/uktrade/ip-filter/actions/runs/14004700362/job/39216976101?pr=71).
---
- ~[ ] [Run the end to end tests for this branch]([https://github.com/uktrade/platform-tools?tab=readme-o …
=> test: Update Codecov action (off-ticket)

.github/dependabot.yml
Hopefully addresses https://uktrade.atlassian.net/browse/DBTP-1924
---
- ~[ ] [Run the end to end tests for this branch]([https://github.com/uktrade/platform-tools?tab=readme-ov-file#regression-tests](https://github.com/uktrade/platform-end-to-end-tests?tab=readme-ov-file#running-the-tests)) and confirm that they are passing~
=> chore: Add schedule and terraform ecosystem to dependabot config (DBTP-1924)

dbt_platform_helper/commands/secrets.py, dbt_platform_helper/constants.py, dbt_platform_helper/domain/config.py, dbt_platform_helper/domain/copilot_environment.py, dbt_platform_helper/domain/database_copy.py, dbt_platform_helper/domain/maintenance_page.py, dbt_platform_helper/domain/pipelines.py, dbt_platform_helper/providers/aws/exceptions.py, dbt_platform_helper/providers/cloudformation.py, dbt_platform_helper/providers/config.py, dbt_platform_helper/providers/config_validator.py, dbt_platform_helper/providers/copilot.py, dbt_platform_helper/providers/io.py, dbt_platform_helper/providers/load_balancers.py, dbt_platform_helper/providers/platform_config_schema.py, dbt_platform_helper/providers/secrets.py, dbt_platform_helper/utils/aws.py, tests/platform_helper/conftest.py, tests/platform_helper/domain/test_conduit.py, tests/platform_helper/domain/test_maintenance_page.py, tests/platform_helper/providers/test_load_balancers.py, tests/platform_helper/utils/test_validation.py
Addresses https://uktrade.atlassian.net/browse/DBTP-1888.
---
~~- [ ] If the work includes user interface changes, before and after screenshots included in description~~
~~- [ ] Includes any applicable changes to the documentation in this code base~~
~~- [ ] Includes link(s) to any applicable changes to the documentation in the [DBT Platform Documentation](https://platform.readme.trade.gov.uk/) (can be to a pull request)~~
~~- [ ] [Run the end to end tests for this branch]([https://github.com/uktrade/platform-tools?tab=readme-ov-file#regression-tests](https://github.com/uktrade/platform-end-to-end-tests?tab=readme-ov-file#running-the-tests)) and confirm that they are passing~~
=> chore: Update TODO comments in code with ticket numbers (DBTP-1888)

.github/dependabot.yml
Addresses https://uktrade.atlassian.net/browse/DBTP-1924.
---
=> chore: Correct typos in dependabot.yml (DBTP-1924)

README.md
Addresses https://uktrade.atlassian.net/browse/DBTP-1842
Force release=please to create a 14.0.0 release.
---
=> feat!: Force version 14.0.0 (DBTP-1842)

terraform/environment-pipelines/buildspec-install-build-tools.yml, terraform/environment-pipelines/buildspec-plan.yml, terraform/postgres/database-copy-pipeline/buildspec-install-build-tools.yml
Add quotes to platform-helper string when retrieving version number from platform-config
---
=> fix: Fix error parsing platform-helper version number (off-ticket)

.github/workflows/create-release.yml
Addresses https://uktrade.atlassian.net/browse/DBTP-1939
Adds in the moving major and minor tags to the release action. This is to allow other uses of the modules to fix to a particular major or minor version.
---
=> fix: Add in moving major and minor version tags to the release (DBTP-1939)

.pre-commit-config.yaml, terraform/environment-pipelines/buildspec-install-build-tools.yml, terraform/environment-pipelines/iam.tf, terraform/postgres/database-copy-pipeline/buildspec-install-build-tools.yml, terraform/postgres/database-copy-pipeline/codepipeline.tf, terraform/postgres/database-copy-pipeline/iam.tf
Add renamed codestar perms
---
=> fix: Fix codestar in database copy (off-ticket)

images/tools/database-copy/clear_db.sql
Addresses https://uktrade.atlassian.net/browse/DBTP-2150
---
=> fix: Update data copy clear script to remove functions, view and sequences (DBTP-2150)

terraform/extensions/locals.tf
Addresses https://uktrade.atlassian.net/browse/DBTP-2153
---
=> fix: Add default value for service-deployment-mode (DBTP-2153)

terraform/datadog/locals.tf, terraform/datadog/main.tf
Addresses https://uktrade.atlassian.net/browse/DBTP-<ticket>.
---
=> feat: Add link to standard dashboard to each service (DBTP-2193)
